/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_SoDoPhong;
import BLL.BLL_ThuePhong;
import DTO.DTO_Phong;
import DTO.DTO_ThuePhong;
import static GUI.GUI_pnl_ChiTietPhong.lblLoaiPhong;
import static GUI.GUI_pnl_ChiTietPhong.lblSoPhong;
import HELPER.HELPER_ChuyenDoi;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.ImageIcon;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ChiTietThuePhong extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnlChiTietPhong
     */
    public GUI_pnl_ChiTietThuePhong() {
        initComponents();
        load();
    }

    public void load() {
        ArrayList<DTO_Phong> arrayPhong = BLL_ThuePhong.selectPhong(GUI_pnl_ThuePhong.index);
        BLL_ThuePhong.loadPhong(arrayPhong, lblSoPhong, lblLoaiPhong, lblTrangThaiPhong);
        ArrayList<DTO_ThuePhong> arrayThuePhong = BLL_ThuePhong.selectThuePhong(GUI_pnl_ThuePhong.index);
        BLL_ThuePhong.loadThuePhong(arrayThuePhong, lblNgayDen, lblThangDen, lblGioPhutDen, lblNgayDi, lblThangDi, lblGioPhutDi, lblTenKhach);

        if (lblTrangThaiPhong.getText().equals("Phòng Trống")) {
            lblIconPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel (3).png")));

        } else {
            if (lblTrangThaiPhong.getText().equals("Có Khách")) {
                lblTrangThaiPhong.setForeground(new Color(255, 142, 113));
            } else if (lblTrangThaiPhong.getText().equals("Đặt Trước")) {
                lblTrangThaiPhong.setForeground(new Color(102, 153, 255));
            } else if (lblTrangThaiPhong.getText().equals("Trả Phòng")) {
                lblTrangThaiPhong.setForeground(new Color(255, 153, 0));
            }
            lblIconPhong.setIcon(new ImageIcon(getClass().getResource("/IMG/hotel (3).png")));
        }

        tongThoiGian();
    }

    public void tongThoiGian() {
        SimpleDateFormat format = new SimpleDateFormat("HH:mm");
        Calendar c1 = Calendar.getInstance();
        Calendar c2 = Calendar.getInstance();
        Date d1 = null;
        Date d2 = null;

        String dateStart = lblGioPhutDen.getText();
        String dateStop = lblGioPhutDi.getText();

        try {
            String ngayDen = HELPER_ChuyenDoi.convertDate("dd-MM", "yyyy-MM-dd", lblNgayDen.getText() + "-" + lblThangDen.getText() + "-" + HELPER_ChuyenDoi.getTimeNow("yy"));
            String ngayDi = HELPER_ChuyenDoi.convertDate("dd-MM", "yyyy-MM-dd", lblNgayDi.getText() + "-" + lblThangDi.getText() + "-" + HELPER_ChuyenDoi.getTimeNow("yy"));
            java.sql.Date date1 = java.sql.Date.valueOf(ngayDen);
            java.sql.Date date2 = java.sql.Date.valueOf(ngayDi);
            c1.setTime(date1);
            c2.setTime(date2);
            d1 = (Date) format.parse(dateStart);
            d2 = (Date) format.parse(dateStop);
        } catch (Exception e) {
            e.printStackTrace();
        }

        long noDay = (c2.getTime().getTime() - c1.getTime().getTime()) / (24 * 3600 * 1000);
        long diff = (d2.getTime() - d1.getTime()) / 1000;
        long diffHours = diff / (60 * 60);
        long diffMinutes = (diff % (60 * 60)) / 60;

        lblTongThoiGian.setText(String.valueOf(noDay + "d " + diffHours + "h " + diffMinutes + "m"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoChiTietThuePhong = new HELPER.PanelShadow();
        lblGioPhutDi = new javax.swing.JLabel();
        lblLoaiPhong = new javax.swing.JLabel();
        lblDichVu = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        lblThangDen = new javax.swing.JLabel();
        spt_1 = new javax.swing.JSeparator();
        lblNgayDen = new javax.swing.JLabel();
        lblSetDaTra = new javax.swing.JLabel();
        lblDaTra = new javax.swing.JLabel();
        lblSoPhong = new javax.swing.JLabel();
        lblThangDi = new javax.swing.JLabel();
        spt_2 = new javax.swing.JSeparator();
        lblTrangThaiPhong = new javax.swing.JLabel();
        lblNgayDi = new javax.swing.JLabel();
        lblIconDongHo = new javax.swing.JLabel();
        lblTongThoiGian = new javax.swing.JLabel();
        lblGioPhutDen = new javax.swing.JLabel();
        lblSetTienPhong = new javax.swing.JLabel();
        lblSetDichVu = new javax.swing.JLabel();
        lblIconPhong = new javax.swing.JLabel();
        lblTenKhach = new javax.swing.JLabel();
        spt_3 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(250, 220));
        setPreferredSize(new java.awt.Dimension(250, 220));

        sdoChiTietThuePhong.setBackground(new java.awt.Color(255, 255, 255));
        sdoChiTietThuePhong.setMinimumSize(new java.awt.Dimension(250, 220));
        sdoChiTietThuePhong.setPreferredSize(new java.awt.Dimension(250, 220));
        sdoChiTietThuePhong.setShadowOpacity(0.3F);
        sdoChiTietThuePhong.setShadowSize(4);
        sdoChiTietThuePhong.setShadowType(HELPER.ShadowType.BOT_RIGHT);
        sdoChiTietThuePhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGioPhutDi.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGioPhutDi.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioPhutDi.setText("19:09");
        sdoChiTietThuePhong.add(lblGioPhutDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 20));

        lblLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiPhong.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblLoaiPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiPhong.setText("Phòng Đơn");
        sdoChiTietThuePhong.add(lblLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 20));

        lblDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblDichVu.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblDichVu.setForeground(new java.awt.Color(153, 153, 153));
        lblDichVu.setText("Dịch Vụ");
        sdoChiTietThuePhong.add(lblDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 50, 30));

        lblTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblTienPhong.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblTienPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblTienPhong.setText("Tiền Phòng");
        sdoChiTietThuePhong.add(lblTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 30));

        lblThangDen.setBackground(new java.awt.Color(255, 255, 255));
        lblThangDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThangDen.setForeground(new java.awt.Color(62, 73, 95));
        lblThangDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThangDen.setText("9");
        lblThangDen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuePhong.add(lblThangDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 20, 30));

        spt_1.setBackground(new java.awt.Color(0, 0, 0));
        spt_1.setForeground(new java.awt.Color(62, 73, 95));
        sdoChiTietThuePhong.add(spt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 20, 10));

        lblNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDen.setForeground(new java.awt.Color(62, 73, 95));
        lblNgayDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayDen.setText("16");
        lblNgayDen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuePhong.add(lblNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 20, -1));

        lblSetDaTra.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDaTra.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetDaTra.setForeground(new java.awt.Color(62, 73, 95));
        lblSetDaTra.setText("500,000");
        sdoChiTietThuePhong.add(lblSetDaTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 60, 30));

        lblDaTra.setBackground(new java.awt.Color(255, 255, 255));
        lblDaTra.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblDaTra.setForeground(new java.awt.Color(153, 153, 153));
        lblDaTra.setText("Đã Trả");
        sdoChiTietThuePhong.add(lblDaTra, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 40, 30));

        lblSoPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhong.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblSoPhong.setForeground(new java.awt.Color(62, 73, 95));
        lblSoPhong.setText("101");
        sdoChiTietThuePhong.add(lblSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        lblThangDi.setBackground(new java.awt.Color(255, 255, 255));
        lblThangDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThangDi.setForeground(new java.awt.Color(62, 73, 95));
        lblThangDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThangDi.setText("9");
        lblThangDi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuePhong.add(lblThangDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 20, 30));

        spt_2.setBackground(new java.awt.Color(0, 0, 0));
        spt_2.setForeground(new java.awt.Color(62, 73, 95));
        sdoChiTietThuePhong.add(spt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 20, 10));

        lblTrangThaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblTrangThaiPhong.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblTrangThaiPhong.setForeground(new java.awt.Color(97, 177, 90));
        lblTrangThaiPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTrangThaiPhong.setText("Phòng Trống");
        sdoChiTietThuePhong.add(lblTrangThaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, 20));

        lblNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDi.setForeground(new java.awt.Color(62, 73, 95));
        lblNgayDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayDi.setText("16");
        lblNgayDi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuePhong.add(lblNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 20, -1));

        lblIconDongHo.setBackground(new java.awt.Color(255, 255, 255));
        lblIconDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clock.png"))); // NOI18N
        sdoChiTietThuePhong.add(lblIconDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 30, 30));

        lblTongThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        lblTongThoiGian.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTongThoiGian.setForeground(new java.awt.Color(255, 102, 102));
        lblTongThoiGian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongThoiGian.setText("30'");
        sdoChiTietThuePhong.add(lblTongThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 70, 30));

        lblGioPhutDen.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGioPhutDen.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioPhutDen.setText("19:09");
        sdoChiTietThuePhong.add(lblGioPhutDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        lblSetTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTienPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetTienPhong.setForeground(new java.awt.Color(62, 73, 95));
        lblSetTienPhong.setText("470,000");
        sdoChiTietThuePhong.add(lblSetTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 70, 30));

        lblSetDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDichVu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetDichVu.setForeground(new java.awt.Color(62, 73, 95));
        lblSetDichVu.setText("140,000");
        sdoChiTietThuePhong.add(lblSetDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 60, 30));

        lblIconPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblIconPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hotel (3).png"))); // NOI18N
        sdoChiTietThuePhong.add(lblIconPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 20, 20));

        lblTenKhach.setBackground(new java.awt.Color(255, 255, 255));
        lblTenKhach.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTenKhach.setForeground(new java.awt.Color(255, 102, 102));
        lblTenKhach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/personal-profile (1).png"))); // NOI18N
        lblTenKhach.setText("G2K Mr.Pii");
        sdoChiTietThuePhong.add(lblTenKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 130, 40));

        spt_3.setForeground(new java.awt.Color(62, 73, 95));
        sdoChiTietThuePhong.add(spt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietThuePhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblDaTra;
    public javax.swing.JLabel lblDichVu;
    private javax.swing.JLabel lblGioPhutDen;
    private javax.swing.JLabel lblGioPhutDi;
    private javax.swing.JLabel lblIconDongHo;
    private javax.swing.JLabel lblIconPhong;
    public javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblNgayDen;
    private javax.swing.JLabel lblNgayDi;
    private javax.swing.JLabel lblSetDaTra;
    private javax.swing.JLabel lblSetDichVu;
    private javax.swing.JLabel lblSetTienPhong;
    private javax.swing.JLabel lblSoPhong;
    private javax.swing.JLabel lblTenKhach;
    private javax.swing.JLabel lblThangDen;
    private javax.swing.JLabel lblThangDi;
    public javax.swing.JLabel lblTienPhong;
    private javax.swing.JLabel lblTongThoiGian;
    private javax.swing.JLabel lblTrangThaiPhong;
    public HELPER.PanelShadow sdoChiTietThuePhong;
    private javax.swing.JSeparator spt_1;
    private javax.swing.JSeparator spt_2;
    private javax.swing.JSeparator spt_3;
    // End of variables declaration//GEN-END:variables
}
