/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ChiTietNhapKho;
import BLL.BLL_NhapKho;
import DTO.DTO_ChiTietNhapKho;
import DTO.DTO_NhapKho;
import HELPER.HELPER_ChuyenDoi;
import java.awt.event.MouseEvent;
import java.util.ArrayList;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ChiTietNhapKho extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnlChiTietNhapKho
     */
    public GUI_pnl_ChiTietNhapKho() {
        initComponents();
        load();
    }

    public void load() {
        ArrayList<DTO_NhapKho> arrayNhapKho = BLL_NhapKho.selectNhapKho(GUI_pnl_QuanLiKho.index);
        BLL_NhapKho.loadNhapKho(arrayNhapKho, lblSetMaPhieu, lblSetNhanVien, lblSetNgayTao);
        ArrayList<DTO_ChiTietNhapKho> arrayChiTietNhapKho = BLL_ChiTietNhapKho.selectChiTietNhapKho(GUI_pnl_QuanLiKho.index);
        BLL_ChiTietNhapKho.loadChiTietNhapKho(arrayChiTietNhapKho, tblChiTietNhapKho);
        int total = 0;
        for (int i = 0; i < tblChiTietNhapKho.getRowCount(); i++) {
            total+=HELPER_ChuyenDoi.getSoInt(tblChiTietNhapKho.getValueAt(i, 3).toString());           
        }
        lblTongTien.setText(HELPER_ChuyenDoi.getSoString(total));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoChiTietNhapKho = new HELPER.PanelShadow();
        lblSetNhanVien = new javax.swing.JLabel();
        lblSetNgayTao = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        scrChiTietNhapKho = new javax.swing.JScrollPane();
        tblChiTietNhapKho = new javax.swing.JTable();
        lblSetMaPhieu = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(350, 250));
        setPreferredSize(new java.awt.Dimension(350, 250));

        sdoChiTietNhapKho.setBackground(new java.awt.Color(255, 255, 255));
        sdoChiTietNhapKho.setMinimumSize(new java.awt.Dimension(350, 210));
        sdoChiTietNhapKho.setPreferredSize(new java.awt.Dimension(350, 210));
        sdoChiTietNhapKho.setShadowOpacity(0.3F);
        sdoChiTietNhapKho.setShadowSize(4);
        sdoChiTietNhapKho.setShadowType(HELPER.ShadowType.BOT_RIGHT);
        sdoChiTietNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdoChiTietNhapKhoMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                sdoChiTietNhapKhoMouseReleased(evt);
            }
        });
        sdoChiTietNhapKho.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNhanVien.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNhanVien.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNhanVien.setText("CherryCe");
        sdoChiTietNhapKho.add(lblSetNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 80, 20));

        lblSetNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNgayTao.setText("22-09-22 12:02");
        sdoChiTietNhapKho.add(lblSetNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 90, 20));

        lblTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblTongTien.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(97, 177, 90));
        lblTongTien.setText("2250,000");
        sdoChiTietNhapKho.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 90, 40));

        lblMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblMaPhieu.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblMaPhieu.setForeground(new java.awt.Color(153, 153, 153));
        lblMaPhieu.setText("Mã Phiếu");
        sdoChiTietNhapKho.add(lblMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 20));

        scrChiTietNhapKho.setBackground(new java.awt.Color(255, 255, 255));

        tblChiTietNhapKho.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        tblChiTietNhapKho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tên Hàng", "Số Lượng", "Giá Nhập", "Tổng Tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblChiTietNhapKho.setRowHeight(20);
        tblChiTietNhapKho.setShowHorizontalLines(false);
        scrChiTietNhapKho.setViewportView(tblChiTietNhapKho);

        sdoChiTietNhapKho.add(scrChiTietNhapKho, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 150));

        lblSetMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetMaPhieu.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetMaPhieu.setForeground(new java.awt.Color(62, 73, 95));
        lblSetMaPhieu.setText("220923001");
        sdoChiTietNhapKho.add(lblSetMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 110, 20));

        lblNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayTao.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayTao.setText("Ngày");
        sdoChiTietNhapKho.add(lblNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 30, 20));

        lblNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        lblNhanVien.setText("Nhân Viên");
        sdoChiTietNhapKho.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 60, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietNhapKho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietNhapKho, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sdoChiTietNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdoChiTietNhapKhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sdoChiTietNhapKhoMouseClicked

    private void sdoChiTietNhapKhoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdoChiTietNhapKhoMouseReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_sdoChiTietNhapKhoMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblMaPhieu;
    public javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblNhanVien;
    public javax.swing.JLabel lblSetMaPhieu;
    public javax.swing.JLabel lblSetNgayTao;
    public javax.swing.JLabel lblSetNhanVien;
    public javax.swing.JLabel lblTongTien;
    private javax.swing.JScrollPane scrChiTietNhapKho;
    public HELPER.PanelShadow sdoChiTietNhapKho;
    private javax.swing.JTable tblChiTietNhapKho;
    // End of variables declaration//GEN-END:variables
}
