/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.GUI_pnl_ChiTietPhong;
import java.awt.GridLayout;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_GiaPhong extends javax.swing.JPanel {

    public static int index;

    /**
     * Creates new form GUI_pnlSoDoPhong
     */
    public GUI_pnl_GiaPhong() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoChucNang = new HELPER.PanelShadow();
        lblGioPhutTuNgay = new javax.swing.JLabel();
        lblGioPhutDenNgay = new javax.swing.JLabel();
        dateTuNgay = new com.toedter.calendar.JDateChooser();
        dateDenNgay = new com.toedter.calendar.JDateChooser();
        lblDenNgay = new javax.swing.JLabel();
        lblTuNgay = new javax.swing.JLabel();
        lblTinhGia = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblSetThoiGian = new javax.swing.JLabel();
        lblSetTongTien = new javax.swing.JLabel();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        lblThoiGian = new javax.swing.JLabel();
        lblKiemTraGia = new javax.swing.JLabel();
        lblLoaiGia = new javax.swing.JLabel();
        cboLoaiGia = new javax.swing.JComboBox<>();
        lblLoaiPhong = new javax.swing.JLabel();
        sdoChuThich = new HELPER.PanelShadow();
        pnlGiaPhong = new javax.swing.JPanel();
        scrGiaPhong = new javax.swing.JScrollPane();
        tblGiaPhong = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 730));
        setPreferredSize(new java.awt.Dimension(1150, 730));

        sdoChucNang.setBackground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setForeground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setMinimumSize(new java.awt.Dimension(1150, 110));
        sdoChucNang.setPreferredSize(new java.awt.Dimension(1150, 110));
        sdoChucNang.setShadowOpacity(0.4F);
        sdoChucNang.setShadowSize(9);
        sdoChucNang.setShadowType(HELPER.ShadowType.BOT);
        sdoChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGioPhutTuNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutTuNgay.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblGioPhutTuNgay.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutTuNgay.setText("00:00");
        lblGioPhutTuNgay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoChucNang.add(lblGioPhutTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 40, 20));

        lblGioPhutDenNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutDenNgay.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblGioPhutDenNgay.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutDenNgay.setText("00:00");
        lblGioPhutDenNgay.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoChucNang.add(lblGioPhutDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 50, 40, 20));

        dateTuNgay.setBackground(new java.awt.Color(255, 255, 255));
        dateTuNgay.setForeground(new java.awt.Color(62, 73, 95));
        dateTuNgay.setDateFormatString("dd-MM-yyyy");
        sdoChucNang.add(dateTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 20));

        dateDenNgay.setBackground(new java.awt.Color(255, 255, 255));
        dateDenNgay.setForeground(new java.awt.Color(62, 73, 95));
        dateDenNgay.setDateFormatString("dd-MM-yyyy");
        sdoChucNang.add(dateDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 100, 20));

        lblDenNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblDenNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDenNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblDenNgay.setText("Đến Ngày");
        sdoChucNang.add(lblDenNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, 20));

        lblTuNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblTuNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTuNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblTuNgay.setText("Từ Ngày");
        sdoChucNang.add(lblTuNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, 20));

        lblTinhGia.setBackground(new java.awt.Color(255, 255, 255));
        lblTinhGia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTinhGia.setForeground(new java.awt.Color(33, 150, 243));
        lblTinhGia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/money-back.png"))); // NOI18N
        lblTinhGia.setText("Tính Giá");
        lblTinhGia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTinhGia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        sdoChucNang.add(lblTinhGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 60, 50));

        lblTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblTongTien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(153, 153, 153));
        lblTongTien.setText("Tổng Tiền");
        sdoChucNang.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 20, -1, 20));

        lblSetThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        lblSetThoiGian.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetThoiGian.setForeground(new java.awt.Color(97, 177, 90));
        lblSetThoiGian.setText("3d 4h 5m");
        sdoChucNang.add(lblSetThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, 80, 20));

        lblSetTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTongTien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetTongTien.setForeground(new java.awt.Color(97, 177, 90));
        lblSetTongTien.setText("1,200,000");
        sdoChucNang.add(lblSetTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 50, 80, 20));

        cboLoaiPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboLoaiPhong.setForeground(new java.awt.Color(62, 73, 95));
        cboLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiPhong.setToolTipText("");
        cboLoaiPhong.setBorder(null);
        sdoChucNang.add(cboLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 20));

        lblThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        lblThoiGian.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThoiGian.setForeground(new java.awt.Color(153, 153, 153));
        lblThoiGian.setText("Thời Gian");
        sdoChucNang.add(lblThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, 20));

        lblKiemTraGia.setBackground(new java.awt.Color(255, 255, 255));
        lblKiemTraGia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblKiemTraGia.setForeground(new java.awt.Color(62, 73, 95));
        lblKiemTraGia.setText("Kiểm Tra Giá");
        sdoChucNang.add(lblKiemTraGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, -1, 20));

        lblLoaiGia.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiGia.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLoaiGia.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiGia.setText("Loại Giá");
        sdoChucNang.add(lblLoaiGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 70, 20));

        cboLoaiGia.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboLoaiGia.setForeground(new java.awt.Color(62, 73, 95));
        cboLoaiGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiGia.setToolTipText("");
        cboLoaiGia.setBorder(null);
        sdoChucNang.add(cboLoaiGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 80, 20));

        lblLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLoaiPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiPhong.setText("Loại Phòng");
        sdoChucNang.add(lblLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        sdoChuThich.setBackground(new java.awt.Color(255, 255, 255));
        sdoChuThich.setForeground(new java.awt.Color(255, 255, 255));
        sdoChuThich.setMinimumSize(new java.awt.Dimension(1150, 70));
        sdoChuThich.setPreferredSize(new java.awt.Dimension(1150, 70));
        sdoChuThich.setShadowOpacity(0.6F);
        sdoChuThich.setShadowSize(9);
        sdoChuThich.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGiaPhong.setBackground(new java.awt.Color(255, 255, 255));
        pnlGiaPhong.setMinimumSize(new java.awt.Dimension(1150, 550));
        pnlGiaPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrGiaPhong.setBackground(new java.awt.Color(255, 255, 255));
        scrGiaPhong.setBorder(null);

        tblGiaPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblGiaPhong.setForeground(new java.awt.Color(62, 73, 95));
        tblGiaPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"
            }
        ));
        tblGiaPhong.setRowHeight(30);
        scrGiaPhong.setViewportView(tblGiaPhong);

        pnlGiaPhong.add(scrGiaPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1130, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pnlGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sdoChuThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(pnlGiaPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdoChuThich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLoaiGia;
    private javax.swing.JComboBox<String> cboLoaiPhong;
    private com.toedter.calendar.JDateChooser dateDenNgay;
    private com.toedter.calendar.JDateChooser dateTuNgay;
    private javax.swing.JLabel lblDenNgay;
    private javax.swing.JLabel lblGioPhutDenNgay;
    private javax.swing.JLabel lblGioPhutTuNgay;
    private javax.swing.JLabel lblKiemTraGia;
    private javax.swing.JLabel lblLoaiGia;
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblSetThoiGian;
    private javax.swing.JLabel lblSetTongTien;
    private javax.swing.JLabel lblThoiGian;
    private javax.swing.JLabel lblTinhGia;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lblTuNgay;
    private javax.swing.JPanel pnlGiaPhong;
    private javax.swing.JScrollPane scrGiaPhong;
    private HELPER.PanelShadow sdoChuThich;
    private HELPER.PanelShadow sdoChucNang;
    private static javax.swing.JTable tblGiaPhong;
    // End of variables declaration//GEN-END:variables
}
