/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_SanPham;
import DTO.DTO_SanPham;
import java.util.ArrayList;

/**
 *
 * @author CherryCe
 */
public class GUI_dal_ThongTinDichVu extends javax.swing.JDialog {

    /**
     * Creates new form GUI_dalThongTinPhong
     */
    public GUI_dal_ThongTinDichVu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        loadSanPham();
    }
    
    public void loadSanPham() {
        ArrayList<DTO_SanPham> array = BLL_SanPham.select();
        BLL_SanPham.loadKhoDichVu(array, tblKhoDichVu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoThongTinPhong = new HELPER.PanelShadow();
        lblSetMaHoaDon = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        lblSoPhong = new javax.swing.JLabel();
        lblSetNhanVien = new javax.swing.JLabel();
        lblSetSoPhong = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblNgayDi = new javax.swing.JLabel();
        lblNgayDen = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblPhieuBanHang = new javax.swing.JLabel();
        lblSetNgayDen = new javax.swing.JLabel();
        lblSetNgayTao = new javax.swing.JLabel();
        lblSetNgayDi = new javax.swing.JLabel();
        lbl_1 = new javax.swing.JLabel();
        lbl_3 = new javax.swing.JLabel();
        lblAll = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        txtGhiChu = new javax.swing.JTextField();
        lblExit = new javax.swing.JLabel();
        sdoKhoDichVu = new HELPER.PanelShadow();
        scrKhoDichVu = new javax.swing.JScrollPane();
        tblKhoDichVu = new javax.swing.JTable();
        sdoDichVu = new HELPER.PanelShadow();
        scrDichVu = new javax.swing.JScrollPane();
        tblDichVu = new javax.swing.JTable();
        sdoChucNang = new HELPER.PanelShadow();
        lblSetDaThanhToan = new javax.swing.JLabel();
        lblSetTongTien = new javax.swing.JLabel();
        lblDaThanhToan = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblThoat = new javax.swing.JLabel();
        lblCapNhat = new javax.swing.JLabel();
        lblInPhieu = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(860, 610));
        setUndecorated(true);

        sdoThongTinPhong.setBackground(new java.awt.Color(255, 255, 255));
        sdoThongTinPhong.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 0, 1, new java.awt.Color(33, 150, 243)));
        sdoThongTinPhong.setMinimumSize(new java.awt.Dimension(860, 130));
        sdoThongTinPhong.setPreferredSize(new java.awt.Dimension(860, 130));
        sdoThongTinPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetMaHoaDon.setBackground(new java.awt.Color(255, 255, 255));
        lblSetMaHoaDon.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetMaHoaDon.setForeground(new java.awt.Color(62, 73, 95));
        lblSetMaHoaDon.setText("220912001");
        sdoThongTinPhong.add(lblSetMaHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 100, 20));

        lblMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblMaPhieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaPhieu.setForeground(new java.awt.Color(153, 153, 153));
        lblMaPhieu.setText("Mã Phiếu");
        sdoThongTinPhong.add(lblMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, 20));

        lblSoPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSoPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblSoPhong.setText("Số Phòng");
        sdoThongTinPhong.add(lblSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, 20));

        lblSetNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNhanVien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNhanVien.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNhanVien.setText("CherryCe");
        sdoThongTinPhong.add(lblSetNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 100, 20));

        lblSetSoPhong.setBackground(new java.awt.Color(97, 177, 90));
        lblSetSoPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetSoPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblSetSoPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSetSoPhong.setText("201");
        lblSetSoPhong.setOpaque(true);
        lblSetSoPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSetSoPhongMouseClicked(evt);
            }
        });
        sdoThongTinPhong.add(lblSetSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 40, 20));

        lblNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        lblNhanVien.setText("Nhân Viên");
        sdoThongTinPhong.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, -1, 20));

        lblNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDi.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayDi.setText("Ngày Đi");
        sdoThongTinPhong.add(lblNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, -1, 20));

        lblNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDen.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayDen.setText("Ngày Đến");
        sdoThongTinPhong.add(lblNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, -1, 20));

        lblGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        lblGhiChu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(153, 153, 153));
        lblGhiChu.setText("Ghi Chú");
        sdoThongTinPhong.add(lblGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 50, -1, 20));

        lblNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayTao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayTao.setText("Ngày Tạo");
        sdoThongTinPhong.add(lblNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 20));

        lblPhieuBanHang.setBackground(new java.awt.Color(255, 255, 255));
        lblPhieuBanHang.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblPhieuBanHang.setForeground(new java.awt.Color(62, 73, 95));
        lblPhieuBanHang.setText("PHIẾU BÁN HÀNG");
        sdoThongTinPhong.add(lblPhieuBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        lblSetNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayDen.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayDen.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNgayDen.setText("16/09/22");
        sdoThongTinPhong.add(lblSetNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 70, 20));

        lblSetNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayTao.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNgayTao.setText("16/09/22 22:08");
        sdoThongTinPhong.add(lblSetNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 50, -1, 20));

        lblSetNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayDi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayDi.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNgayDi.setText("16/09/22");
        sdoThongTinPhong.add(lblSetNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, 70, 20));

        lbl_1.setBackground(new java.awt.Color(255, 102, 102));
        lbl_1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_1.setText("Đồ Uống");
        lbl_1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_1.setOpaque(true);
        sdoThongTinPhong.add(lbl_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 80, 70, 30));

        lbl_3.setBackground(new java.awt.Color(255, 102, 102));
        lbl_3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_3.setForeground(new java.awt.Color(255, 255, 255));
        lbl_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_3.setText("Di Chuyển");
        lbl_3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_3.setOpaque(true);
        sdoThongTinPhong.add(lbl_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 80, 70, 30));

        lblAll.setBackground(new java.awt.Color(255, 102, 102));
        lblAll.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblAll.setForeground(new java.awt.Color(255, 255, 255));
        lblAll.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAll.setText("ALL");
        lblAll.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAll.setOpaque(true);
        sdoThongTinPhong.add(lblAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 40, 30));

        lbl_2.setBackground(new java.awt.Color(255, 102, 102));
        lbl_2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lbl_2.setForeground(new java.awt.Color(255, 255, 255));
        lbl_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_2.setText("Thức Ăn");
        lbl_2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbl_2.setOpaque(true);
        sdoThongTinPhong.add(lbl_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 80, 70, 30));

        txtGhiChu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(62, 73, 95));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });
        sdoThongTinPhong.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 50, 190, 20));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (1).png"))); // NOI18N
        sdoThongTinPhong.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 10, 30, 30));

        sdoKhoDichVu.setBackground(new java.awt.Color(255, 255, 255));
        sdoKhoDichVu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 0, 0, new java.awt.Color(33, 150, 243)));
        sdoKhoDichVu.setMinimumSize(new java.awt.Dimension(390, 430));
        sdoKhoDichVu.setPreferredSize(new java.awt.Dimension(390, 430));
        sdoKhoDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrKhoDichVu.setBackground(new java.awt.Color(255, 255, 255));
        scrKhoDichVu.setBorder(null);

        tblKhoDichVu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblKhoDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hàng", "Tên Hàng", "Giá Bán", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblKhoDichVu.setRowHeight(30);
        tblKhoDichVu.setShowHorizontalLines(false);
        scrKhoDichVu.setViewportView(tblKhoDichVu);
        if (tblKhoDichVu.getColumnModel().getColumnCount() > 0) {
            tblKhoDichVu.getColumnModel().getColumn(3).setMaxWidth(40);
        }

        sdoKhoDichVu.add(scrKhoDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 350, 390));

        sdoDichVu.setBackground(new java.awt.Color(255, 255, 255));
        sdoDichVu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 1, new java.awt.Color(33, 150, 243)));
        sdoDichVu.setMinimumSize(new java.awt.Dimension(470, 430));
        sdoDichVu.setPreferredSize(new java.awt.Dimension(470, 430));
        sdoDichVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrDichVu.setBackground(new java.awt.Color(255, 255, 255));
        scrDichVu.setBorder(null);

        tblDichVu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblDichVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hàng", "Tên Hàng", "Số Lượng", "Đơn Giá", "Thành Tiền", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDichVu.setRowHeight(30);
        tblDichVu.setShowHorizontalLines(false);
        scrDichVu.setViewportView(tblDichVu);
        if (tblDichVu.getColumnModel().getColumnCount() > 0) {
            tblDichVu.getColumnModel().getColumn(5).setMaxWidth(40);
        }

        sdoDichVu.add(scrDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 430, 390));

        sdoChucNang.setBackground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 1, 1, 1, new java.awt.Color(33, 150, 243)));
        sdoChucNang.setMinimumSize(new java.awt.Dimension(860, 50));
        sdoChucNang.setPreferredSize(new java.awt.Dimension(860, 50));
        sdoChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetDaThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        lblSetDaThanhToan.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetDaThanhToan.setForeground(new java.awt.Color(97, 177, 90));
        lblSetDaThanhToan.setText("220912001");
        sdoChucNang.add(lblSetDaThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 90, 30));

        lblSetTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblSetTongTien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetTongTien.setForeground(new java.awt.Color(97, 177, 90));
        lblSetTongTien.setText("220912001");
        sdoChucNang.add(lblSetTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 90, 30));

        lblDaThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        lblDaThanhToan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblDaThanhToan.setForeground(new java.awt.Color(153, 153, 153));
        lblDaThanhToan.setText("Đã Thanh Toán");
        sdoChucNang.add(lblDaThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, 30));

        lblTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblTongTien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(153, 153, 153));
        lblTongTien.setText("Tổng Tiền");
        sdoChucNang.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        lblThoat.setBackground(new java.awt.Color(255, 255, 255));
        lblThoat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(33, 150, 243));
        lblThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/logout (6).png"))); // NOI18N
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });
        sdoChucNang.add(lblThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 10, 80, 30));

        lblCapNhat.setBackground(new java.awt.Color(255, 255, 255));
        lblCapNhat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblCapNhat.setForeground(new java.awt.Color(33, 150, 243));
        lblCapNhat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCapNhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/upgrade (3).png"))); // NOI18N
        lblCapNhat.setText("Cập Nhật");
        sdoChucNang.add(lblCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 10, 100, 30));

        lblInPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblInPhieu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblInPhieu.setForeground(new java.awt.Color(33, 150, 243));
        lblInPhieu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInPhieu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/bill (3).png"))); // NOI18N
        lblInPhieu.setText("In Phiếu");
        sdoChucNang.add(lblInPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 90, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoThongTinPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoKhoDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdoDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoThongTinPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sdoKhoDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdoDichVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(sdoChucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_lblThoatMouseClicked

    private void lblSetSoPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSetSoPhongMouseClicked
        // TODO add your handling code here:
        new GUI_dal_ChonPhong(null, true).setVisible(true);
    }//GEN-LAST:event_lblSetSoPhongMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_ThongTinDichVu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dal_ThongTinDichVu dialog = new GUI_dal_ThongTinDichVu(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAll;
    private javax.swing.JLabel lblCapNhat;
    private javax.swing.JLabel lblDaThanhToan;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblInPhieu;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblNgayDen;
    private javax.swing.JLabel lblNgayDi;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPhieuBanHang;
    private javax.swing.JLabel lblSetDaThanhToan;
    private javax.swing.JLabel lblSetMaHoaDon;
    private javax.swing.JLabel lblSetNgayDen;
    private javax.swing.JLabel lblSetNgayDi;
    private javax.swing.JLabel lblSetNgayTao;
    private javax.swing.JLabel lblSetNhanVien;
    private javax.swing.JLabel lblSetSoPhong;
    private javax.swing.JLabel lblSetTongTien;
    private javax.swing.JLabel lblSoPhong;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JScrollPane scrDichVu;
    private javax.swing.JScrollPane scrKhoDichVu;
    private HELPER.PanelShadow sdoChucNang;
    private HELPER.PanelShadow sdoDichVu;
    private HELPER.PanelShadow sdoKhoDichVu;
    private HELPER.PanelShadow sdoThongTinPhong;
    private javax.swing.JTable tblDichVu;
    private javax.swing.JTable tblKhoDichVu;
    private javax.swing.JTextField txtGhiChu;
    // End of variables declaration//GEN-END:variables
}
