/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_QuenMatKhau extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnlDangKi
     */
    public GUI_pnl_QuenMatKhau() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuenMatKhau = new javax.swing.JPanel();
        lblShowHiddenMatKhau = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblSetWebsite = new javax.swing.JLabel();
        lblWebsite = new javax.swing.JLabel();
        lblSetHoTro = new javax.swing.JLabel();
        lblHoTro = new javax.swing.JLabel();
        lblIconTraLoi = new javax.swing.JLabel();
        psdMatKhau = new javax.swing.JPasswordField();
        lblIconBaoMat = new javax.swing.JLabel();
        txtTraLoi = new javax.swing.JTextField();
        cboBaoMat = new javax.swing.JComboBox<>();
        txtTaiKhoan = new javax.swing.JTextField();
        lblIconTaiKhoan = new javax.swing.JLabel();
        lblIconMatKhau = new javax.swing.JLabel();
        lblXacThuc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(400, 450));
        setPreferredSize(new java.awt.Dimension(400, 450));

        pnlQuenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        pnlQuenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 1, new java.awt.Color(33, 150, 243)));
        pnlQuenMatKhau.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblShowHiddenMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblShowHiddenMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/hidden (1).png"))); // NOI18N
        lblShowHiddenMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(62, 73, 95)));
        lblShowHiddenMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowHiddenMatKhauMouseClicked(evt);
            }
        });
        pnlQuenMatKhau.add(lblShowHiddenMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 30, 30));

        lblExit.setBackground(new java.awt.Color(255, 255, 255));
        lblExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (4).png"))); // NOI18N
        lblExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExitMouseClicked(evt);
            }
        });
        pnlQuenMatKhau.add(lblExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 20, 20));

        lblSetWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblSetWebsite.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblSetWebsite.setForeground(new java.awt.Color(62, 73, 95));
        lblSetWebsite.setText("MrPii.2k3");
        pnlQuenMatKhau.add(lblSetWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(319, 420, -1, 20));

        lblWebsite.setBackground(new java.awt.Color(255, 255, 255));
        lblWebsite.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblWebsite.setForeground(new java.awt.Color(153, 153, 153));
        lblWebsite.setText("Website:");
        pnlQuenMatKhau.add(lblWebsite, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 420, -1, 20));

        lblSetHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblSetHoTro.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblSetHoTro.setForeground(new java.awt.Color(62, 73, 95));
        lblSetHoTro.setText("Game2K");
        pnlQuenMatKhau.add(lblSetHoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 420, -1, 20));

        lblHoTro.setBackground(new java.awt.Color(255, 255, 255));
        lblHoTro.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblHoTro.setForeground(new java.awt.Color(153, 153, 153));
        lblHoTro.setText("Hỗ Trợ:");
        pnlQuenMatKhau.add(lblHoTro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, 20));

        lblIconTraLoi.setBackground(new java.awt.Color(255, 255, 255));
        lblIconTraLoi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconTraLoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/conversation.png"))); // NOI18N
        pnlQuenMatKhau.add(lblIconTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, 30));

        psdMatKhau.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        psdMatKhau.setForeground(new java.awt.Color(62, 73, 95));
        psdMatKhau.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(62, 73, 95)));
        pnlQuenMatKhau.add(psdMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 270, 30));

        lblIconBaoMat.setBackground(new java.awt.Color(255, 255, 255));
        lblIconBaoMat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIconBaoMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/iconfinder-securityprotectlockshield04-4021479_113137.png"))); // NOI18N
        pnlQuenMatKhau.add(lblIconBaoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        txtTraLoi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtTraLoi.setForeground(new java.awt.Color(62, 73, 95));
        txtTraLoi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTraLoi.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTraLoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTraLoiActionPerformed(evt);
            }
        });
        pnlQuenMatKhau.add(txtTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 300, 30));

        cboBaoMat.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboBaoMat.setForeground(new java.awt.Color(62, 73, 95));
        cboBaoMat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày Sinh Của Bạn", "Nơi Sinh Của Bạn", "Màu Bạn Yêu Thích", "Con Vật Bạn Thích" }));
        cboBaoMat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlQuenMatKhau.add(cboBaoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 300, 30));

        txtTaiKhoan.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        txtTaiKhoan.setForeground(new java.awt.Color(62, 73, 95));
        txtTaiKhoan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });
        pnlQuenMatKhau.add(txtTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 300, 30));

        lblIconTaiKhoan.setBackground(new java.awt.Color(255, 255, 255));
        lblIconTaiKhoan.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblIconTaiKhoan.setForeground(new java.awt.Color(153, 153, 153));
        lblIconTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/profile-user.png"))); // NOI18N
        pnlQuenMatKhau.add(lblIconTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 30, 30));

        lblIconMatKhau.setBackground(new java.awt.Color(255, 255, 255));
        lblIconMatKhau.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblIconMatKhau.setForeground(new java.awt.Color(153, 153, 153));
        lblIconMatKhau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/padlock.png"))); // NOI18N
        pnlQuenMatKhau.add(lblIconMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 30, 30));

        lblXacThuc.setBackground(new java.awt.Color(62, 73, 95));
        lblXacThuc.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblXacThuc.setForeground(new java.awt.Color(255, 255, 255));
        lblXacThuc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblXacThuc.setText("XÁC THỰC");
        lblXacThuc.setOpaque(true);
        lblXacThuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblXacThucMouseClicked(evt);
            }
        });
        pnlQuenMatKhau.add(lblXacThuc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 300, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlQuenMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed

    private void txtTraLoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTraLoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTraLoiActionPerformed

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblShowHiddenMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowHiddenMatKhauMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_lblShowHiddenMatKhauMouseClicked

    private void lblXacThucMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblXacThucMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblXacThucMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboBaoMat;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblHoTro;
    private javax.swing.JLabel lblIconBaoMat;
    private javax.swing.JLabel lblIconMatKhau;
    private javax.swing.JLabel lblIconTaiKhoan;
    private javax.swing.JLabel lblIconTraLoi;
    private javax.swing.JLabel lblSetHoTro;
    private javax.swing.JLabel lblSetWebsite;
    private javax.swing.JLabel lblShowHiddenMatKhau;
    private javax.swing.JLabel lblWebsite;
    private javax.swing.JLabel lblXacThuc;
    private javax.swing.JPanel pnlQuenMatKhau;
    private javax.swing.JPasswordField psdMatKhau;
    private javax.swing.JTextField txtTaiKhoan;
    private javax.swing.JTextField txtTraLoi;
    // End of variables declaration//GEN-END:variables
}
