/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ThuNgan;
import BLL.BLL_ThuePhong;
import DTO.DTO_Phong;
import DTO.DTO_ThuePhong;
import HELPER.HELPER_ChuyenDoi;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.text.SimpleDateFormat;
import java.time.Duration;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.BorderFactory;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_ChiTietThuNgan extends javax.swing.JPanel {
    
    long diffInDay;
    long diffInHours;
    long diffInMinutes;

    /**
     * Creates new form GUI_pnlChiTietPhong
     */
    public GUI_pnl_ChiTietThuNgan() {
        initComponents();
        load();
    }

    public void load() {
        ArrayList<DTO_Phong> arrayPhong = BLL_ThuNgan.selectPhong(GUI_pnl_ThuNgan.index);
        BLL_ThuNgan.loadPhong(arrayPhong, lblSoPhong, lblLoaiPhong);
        ArrayList<DTO_ThuePhong> arrayThuePhong = BLL_ThuNgan.selectThuePhong(GUI_pnl_ThuNgan.index);
        BLL_ThuNgan.loadThuePhong(arrayThuePhong, lblNgayDen, lblThangDen, lblGioPhutDen, lblNgayDi, lblThangDi, lblGioPhutDi, lblTongTien, lblSetMaPhieu, lblSetNgay, lblSetGio, lblLoaiThanhToan, lblNhanVien);
        tongThoiGian();
    }

    public void tongThoiGian() {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm");
        LocalDateTime dateTimeDen = LocalDateTime.parse(lblNgayDen.getText() + "-" + lblThangDen.getText() + "-" + HELPER_ChuyenDoi.getTimeNow("yyyy") + " " + lblGioPhutDen.getText(), formatter);
        LocalDateTime dateTimeDi = LocalDateTime.parse(lblNgayDi.getText() + "-" + lblThangDi.getText() + "-" + HELPER_ChuyenDoi.getTimeNow("yyyy") + " " + lblGioPhutDi.getText(), formatter);
        diffInDay = Duration.between(dateTimeDen, dateTimeDi).toDays();
        diffInHours = Duration.between(dateTimeDen, dateTimeDi).toHours() - diffInDay * 24;
        diffInMinutes = (Duration.between(dateTimeDen, dateTimeDi).toMinutes() - diffInDay * 60 * 24) % 60;
        lblTongThoiGian.setText(String.valueOf(diffInDay + "d " + diffInHours + "h " + diffInMinutes + "m"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoChiTietThuNgan = new HELPER.PanelShadow();
        lblGioPhutDi = new javax.swing.JLabel();
        lblLoaiTien = new javax.swing.JLabel();
        lblLoaiThanhToan = new javax.swing.JLabel();
        lblLoaiPhong = new javax.swing.JLabel();
        spt_3 = new javax.swing.JSeparator();
        lblNgay = new javax.swing.JLabel();
        lblMaPhieu = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblThangDen = new javax.swing.JLabel();
        spt_1 = new javax.swing.JSeparator();
        lblNgayDen = new javax.swing.JLabel();
        lblSetGio = new javax.swing.JLabel();
        lblGio = new javax.swing.JLabel();
        lblSoPhong = new javax.swing.JLabel();
        lblThangDi = new javax.swing.JLabel();
        spt_2 = new javax.swing.JSeparator();
        lblTongTien = new javax.swing.JLabel();
        lblNgayDi = new javax.swing.JLabel();
        lblIconDongHo = new javax.swing.JLabel();
        lblTongThoiGian = new javax.swing.JLabel();
        lblGioPhutDen = new javax.swing.JLabel();
        lblSetMaPhieu = new javax.swing.JLabel();
        lblSetNgay = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(250, 220));
        setPreferredSize(new java.awt.Dimension(250, 220));

        sdoChiTietThuNgan.setBackground(new java.awt.Color(255, 255, 255));
        sdoChiTietThuNgan.setMinimumSize(new java.awt.Dimension(250, 220));
        sdoChiTietThuNgan.setPreferredSize(new java.awt.Dimension(250, 220));
        sdoChiTietThuNgan.setShadowOpacity(0.3F);
        sdoChiTietThuNgan.setShadowSize(4);
        sdoChiTietThuNgan.setShadowType(HELPER.ShadowType.BOT_RIGHT);
        sdoChiTietThuNgan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                sdoChiTietThuNganMouseMoved(evt);
            }
        });
        sdoChiTietThuNgan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sdoChiTietThuNganMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                sdoChiTietThuNganMouseExited(evt);
            }
        });
        sdoChiTietThuNgan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblGioPhutDi.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGioPhutDi.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioPhutDi.setText("19:09");
        sdoChiTietThuNgan.add(lblGioPhutDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 40, 20));

        lblLoaiTien.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiTien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLoaiTien.setForeground(new java.awt.Color(62, 73, 95));
        lblLoaiTien.setText("Tiền Mặt");
        sdoChiTietThuNgan.add(lblLoaiTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        lblLoaiThanhToan.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiThanhToan.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLoaiThanhToan.setForeground(new java.awt.Color(62, 73, 95));
        lblLoaiThanhToan.setText("Hóa Đơn");
        sdoChiTietThuNgan.add(lblLoaiThanhToan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, 30));

        lblLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiPhong.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblLoaiPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiPhong.setText("Phòng Đơn");
        sdoChiTietThuNgan.add(lblLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 100, 20));

        spt_3.setForeground(new java.awt.Color(62, 73, 95));
        sdoChiTietThuNgan.add(spt_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 10));

        lblNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblNgay.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblNgay.setText("Ngày");
        sdoChiTietThuNgan.add(lblNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, 40, 20));

        lblMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblMaPhieu.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMaPhieu.setForeground(new java.awt.Color(153, 153, 153));
        lblMaPhieu.setText("Mã Phiếu");
        sdoChiTietThuNgan.add(lblMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 50, 20));

        lblNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(62, 73, 95));
        lblNhanVien.setText("CherryCe");
        sdoChiTietThuNgan.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 60, 30));

        lblThangDen.setBackground(new java.awt.Color(255, 255, 255));
        lblThangDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThangDen.setForeground(new java.awt.Color(62, 73, 95));
        lblThangDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThangDen.setText("9");
        lblThangDen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuNgan.add(lblThangDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 20, 30));

        spt_1.setBackground(new java.awt.Color(0, 0, 0));
        spt_1.setForeground(new java.awt.Color(62, 73, 95));
        sdoChiTietThuNgan.add(spt_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 20, 10));

        lblNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDen.setForeground(new java.awt.Color(62, 73, 95));
        lblNgayDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayDen.setText("16");
        lblNgayDen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuNgan.add(lblNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 20, -1));

        lblSetGio.setBackground(new java.awt.Color(255, 255, 255));
        lblSetGio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetGio.setForeground(new java.awt.Color(62, 73, 95));
        lblSetGio.setText("19:09");
        sdoChiTietThuNgan.add(lblSetGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 40, 20));

        lblGio.setBackground(new java.awt.Color(255, 255, 255));
        lblGio.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblGio.setForeground(new java.awt.Color(153, 153, 153));
        lblGio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGio.setText("Giờ");
        sdoChiTietThuNgan.add(lblGio, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 40, 20));

        lblSoPhong.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblSoPhong.setForeground(new java.awt.Color(62, 73, 95));
        lblSoPhong.setText("101");
        sdoChiTietThuNgan.add(lblSoPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 40, -1));

        lblThangDi.setBackground(new java.awt.Color(255, 255, 255));
        lblThangDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThangDi.setForeground(new java.awt.Color(62, 73, 95));
        lblThangDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblThangDi.setText("9");
        lblThangDi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuNgan.add(lblThangDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 20, 30));

        spt_2.setBackground(new java.awt.Color(0, 0, 0));
        spt_2.setForeground(new java.awt.Color(62, 73, 95));
        sdoChiTietThuNgan.add(spt_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 20, 10));

        lblTongTien.setBackground(new java.awt.Color(255, 255, 255));
        lblTongTien.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblTongTien.setForeground(new java.awt.Color(255, 102, 102));
        lblTongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongTien.setText("525,000");
        lblTongTien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuNgan.add(lblTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 80, -1));

        lblNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDi.setForeground(new java.awt.Color(62, 73, 95));
        lblNgayDi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNgayDi.setText("16");
        lblNgayDi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoChiTietThuNgan.add(lblNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 20, -1));

        lblIconDongHo.setBackground(new java.awt.Color(255, 255, 255));
        lblIconDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/clock.png"))); // NOI18N
        sdoChiTietThuNgan.add(lblIconDongHo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 30, 30));

        lblTongThoiGian.setBackground(new java.awt.Color(255, 255, 255));
        lblTongThoiGian.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTongThoiGian.setForeground(new java.awt.Color(255, 102, 102));
        lblTongThoiGian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTongThoiGian.setText("30'");
        sdoChiTietThuNgan.add(lblTongThoiGian, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 90, 30));

        lblGioPhutDen.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGioPhutDen.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutDen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGioPhutDen.setText("19:09");
        sdoChiTietThuNgan.add(lblGioPhutDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 40, 20));

        lblSetMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetMaPhieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetMaPhieu.setForeground(new java.awt.Color(62, 73, 95));
        lblSetMaPhieu.setText("220922001");
        sdoChiTietThuNgan.add(lblSetMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 80, 20));

        lblSetNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSetNgay.setForeground(new java.awt.Color(62, 73, 95));
        lblSetNgay.setText("22/09/22");
        sdoChiTietThuNgan.add(lblSetNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 70, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietThuNgan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoChiTietThuNgan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void sdoChiTietThuNganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdoChiTietThuNganMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_sdoChiTietThuNganMouseClicked

    private void sdoChiTietThuNganMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdoChiTietThuNganMouseMoved
        // TODO add your handling code here:
        sdoChiTietThuNgan.setBorder(BorderFactory.createMatteBorder(1, 1, 1, 1, new Color(33, 150, 243)));
    }//GEN-LAST:event_sdoChiTietThuNganMouseMoved

    private void sdoChiTietThuNganMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sdoChiTietThuNganMouseExited
        // TODO add your handling code here:
        sdoChiTietThuNgan.setBorder(null);
    }//GEN-LAST:event_sdoChiTietThuNganMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lblGio;
    private javax.swing.JLabel lblGioPhutDen;
    private javax.swing.JLabel lblGioPhutDi;
    private javax.swing.JLabel lblIconDongHo;
    public javax.swing.JLabel lblLoaiPhong;
    public javax.swing.JLabel lblLoaiThanhToan;
    public javax.swing.JLabel lblLoaiTien;
    public javax.swing.JLabel lblMaPhieu;
    public javax.swing.JLabel lblNgay;
    private javax.swing.JLabel lblNgayDen;
    private javax.swing.JLabel lblNgayDi;
    public javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSetGio;
    private javax.swing.JLabel lblSetMaPhieu;
    private javax.swing.JLabel lblSetNgay;
    private javax.swing.JLabel lblSoPhong;
    private javax.swing.JLabel lblThangDen;
    private javax.swing.JLabel lblThangDi;
    private javax.swing.JLabel lblTongThoiGian;
    private javax.swing.JLabel lblTongTien;
    public HELPER.PanelShadow sdoChiTietThuNgan;
    private javax.swing.JSeparator spt_1;
    private javax.swing.JSeparator spt_2;
    private javax.swing.JSeparator spt_3;
    // End of variables declaration//GEN-END:variables
}
