/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_MaTenLoai;
import BLL.BLL_NhanVien;
import DAL.DAL_NhanVien;
import DTO.DTO_NhanVien;
import HELPER.HELPER_ChuyenDoi;
import HELPER.HELPER_ShowHinhAnh;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author CherryCe
 */
public class GUI_pnl_DatPhong extends javax.swing.JPanel {

    public static String maNhanVien;

    /**
     * Creates new form GUI_pnl_NhanVien
     */
    public GUI_pnl_DatPhong() {
        initComponents();
        load();
    }

    public void validate() {
        Calendar calendar = Calendar.getInstance();
        calendar.add(Calendar.YEAR, -18);
        dateNgayDi.setMaxSelectableDate(calendar.getTime());
    }

    public void add() {
//        DTO_NhanVien nhanVien = new DTO_NhanVien(txtMaPhieu.getText(), txtGhiChu.getText(), String.valueOf(cboGioiTinh.getSelectedItem()).equals("Nam") ? 1 : 0, dateNgayDi.getDate(), txtTienCoc.getText(), txtCMND.getText(), String.valueOf(cboChucVu.getSelectedItem()), HELPER_ChuyenDoi.getSoInt(txtLuong.getText()), HELPER_ChuyenDoi.getNgayDate("dd-MM-yy HH:mm", HELPER_ChuyenDoi.getTimeNow("dd-MM-yy HH:mm")), String.valueOf(cboLoaiPhong.getSelectedItem()).equals("Online") ? 1 : 0);
//        BLL_NhanVien.add(nhanVien);
    }

    public void delete(int index) {
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        } else {
            int choice = JOptionPane.showConfirmDialog(this, "Bạn Có Muốn Xóa Không ?", "Xóa", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                int indexs[] = tblDatPhong.getSelectedRows();
                for (int i = 0; i < indexs.length; i++) {
                    String maNhanVien = tblDatPhong.getValueAt(indexs[i], 0).toString();
                    BLL_NhanVien.delete(maNhanVien);
                }
            }
            return;
        }
    }

    public void edit(int index) {
        if (index < 0) {
            JOptionPane.showMessageDialog(this, "Bạn Chưa Chọn Dòng Cần Sửa");
        }
//        DTO_NhanVien nhanVien = new DTO_NhanVien(txtMaPhieu.getText(), txtGhiChu.getText(), String.valueOf(cboGioiTinh.getSelectedItem()).equals("Nam") ? 1 : 0, dateNgayDi.getDate(), txtTienCoc.getText(), txtCMND.getText(), String.valueOf(cboChucVu.getSelectedItem()), HELPER_ChuyenDoi.getSoInt(txtLuong.getText()), HELPER_ChuyenDoi.getNgayDate("dd-MM-yy HH:mm", lblSetNgayTao.getText()), String.valueOf(cboLoaiPhong.getSelectedItem()).equals("Online") ? 1 : 0);
//        BLL_NhanVien.edit(nhanVien);
    }

    public void reset() {
//        txtMaPhieu.setText(null);
//        txtGhiChu.setText(null);
//        cboGioiTinh.setSelectedItem("Nam");
//        dateNgayDi.setDate(null);
//        txtTienCoc.setText(null);
//        txtCMND.setText(null);
//        cboChucVu.setSelectedItem("Nhân Viên");
//        txtLuong.setText(null);
        lblSetNgayTao.setText(null);
        cboLoaiPhong.setSelectedItem("Offline");
    }

    public void fill(int index) {
//        txtMaPhieu.setText(tblDatPhong.getValueAt(index, 0).toString());
//        txtGhiChu.setText(tblDatPhong.getValueAt(index, 1).toString());
//        cboGioiTinh.setSelectedItem(tblDatPhong.getValueAt(index, 2).toString());
//        dateNgayDi.setDate(HELPER_ChuyenDoi.getNgayDate("dd-MM-yyyy", tblDatPhong.getValueAt(index, 3).toString()));
//        txtTienCoc.setText(tblDatPhong.getValueAt(index, 4).toString());
//        txtCMND.setText(tblDatPhong.getValueAt(index, 5).toString());
//        cboChucVu.setSelectedItem(tblDatPhong.getValueAt(index, 6).toString());
//        txtLuong.setText(tblDatPhong.getValueAt(index, 7).toString());
        lblSetNgayTao.setText(tblDatPhong.getValueAt(index, 8).toString());
        cboLoaiPhong.setSelectedItem(tblDatPhong.getValueAt(index, 9).toString());
    }

    public void load() {
        ArrayList<DTO_NhanVien> array = BLL_NhanVien.select();
        new BLL_NhanVien().load(array, tblDatPhong);
    }

    public void loadTaiKhoan() {
        new GUI_dal_TaiKhoan(null, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoFormChinh = new HELPER.PanelShadow();
        lblTimKiem = new javax.swing.JLabel();
        lblLamMoi = new javax.swing.JLabel();
        lblLoaiPhong = new javax.swing.JLabel();
        txtTienCoc = new javax.swing.JTextField();
        txtGhiChu = new javax.swing.JTextField();
        lblDanhSachDatPhong = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblNgayDi = new javax.swing.JLabel();
        lblNgayDen = new javax.swing.JLabel();
        lblTenKhach = new javax.swing.JLabel();
        lblSoLuong = new javax.swing.JLabel();
        lblTienCoc = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblGhiChu = new javax.swing.JLabel();
        lblLoaiKhach = new javax.swing.JLabel();
        cboLoaiPhong = new javax.swing.JComboBox<>();
        lblSetNgayTao = new javax.swing.JLabel();
        dateNgayDi = new com.toedter.calendar.JDateChooser();
        lblMaPhieu = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        dateNgayDen = new com.toedter.calendar.JDateChooser();
        cboLoaiKhach = new javax.swing.JComboBox<>();
        txtTenKhach = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtTimKiem = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        lblThem = new javax.swing.JLabel();
        lblSetMaPhieu = new javax.swing.JLabel();
        lblGioPhutVao = new javax.swing.JLabel();
        lblGioPhutRa = new javax.swing.JLabel();
        sdoDatPhong = new HELPER.PanelShadow();
        scrDatPhong = new javax.swing.JScrollPane();
        tblDatPhong = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1150, 730));
        setPreferredSize(new java.awt.Dimension(1150, 730));

        sdoFormChinh.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh.setMinimumSize(new java.awt.Dimension(1150, 290));
        sdoFormChinh.setPreferredSize(new java.awt.Dimension(1150, 290));
        sdoFormChinh.setShadowOpacity(0.4F);
        sdoFormChinh.setShadowSize(9);
        sdoFormChinh.setShadowType(HELPER.ShadowType.BOT);
        sdoFormChinh.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTimKiem.setBackground(new java.awt.Color(255, 255, 255));
        lblTimKiem.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblTimKiem.setForeground(new java.awt.Color(33, 150, 243));
        lblTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/magnifier (2).png"))); // NOI18N
        lblTimKiem.setText("Tìm Kiếm");
        lblTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTimKiemMouseClicked(evt);
            }
        });
        sdoFormChinh.add(lblTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 230, 90, 30));

        lblLamMoi.setBackground(new java.awt.Color(255, 255, 255));
        lblLamMoi.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblLamMoi.setForeground(new java.awt.Color(33, 150, 243));
        lblLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/circle-of-two-clockwise-arrows-rotation.png"))); // NOI18N
        lblLamMoi.setText("Làm Mới");
        lblLamMoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLamMoiMouseClicked(evt);
            }
        });
        sdoFormChinh.add(lblLamMoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 80, 30));

        lblLoaiPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLoaiPhong.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiPhong.setText("Loại Phòng");
        sdoFormChinh.add(lblLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 70, 20));

        txtTienCoc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtTienCoc.setForeground(new java.awt.Color(62, 73, 95));
        txtTienCoc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTienCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienCocActionPerformed(evt);
            }
        });
        txtTienCoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTienCocKeyReleased(evt);
            }
        });
        sdoFormChinh.add(txtTienCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 70, 20));

        txtGhiChu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtGhiChu.setForeground(new java.awt.Color(62, 73, 95));
        txtGhiChu.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtGhiChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGhiChuActionPerformed(evt);
            }
        });
        txtGhiChu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGhiChuKeyReleased(evt);
            }
        });
        sdoFormChinh.add(txtGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 540, 20));

        lblDanhSachDatPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblDanhSachDatPhong.setFont(new java.awt.Font("Calibri", 1, 20)); // NOI18N
        lblDanhSachDatPhong.setForeground(new java.awt.Color(62, 73, 95));
        lblDanhSachDatPhong.setText("DANH SÁCH ĐẶT PHÒNG");
        sdoFormChinh.add(lblDanhSachDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 30));

        lblNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayTao.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayTao.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayTao.setText("Ngày Tạo ");
        sdoFormChinh.add(lblNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 50, 60, 20));

        lblNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDi.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDi.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayDi.setText("Ngày Đi ");
        sdoFormChinh.add(lblNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 50, 20));

        lblNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        lblNgayDen.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNgayDen.setForeground(new java.awt.Color(153, 153, 153));
        lblNgayDen.setText("Ngày Đến ");
        sdoFormChinh.add(lblNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 20));

        lblTenKhach.setBackground(new java.awt.Color(255, 255, 255));
        lblTenKhach.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTenKhach.setForeground(new java.awt.Color(153, 153, 153));
        lblTenKhach.setText("Tên Khách");
        sdoFormChinh.add(lblTenKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 70, 20));

        lblSoLuong.setBackground(new java.awt.Color(255, 255, 255));
        lblSoLuong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSoLuong.setForeground(new java.awt.Color(153, 153, 153));
        lblSoLuong.setText("Số Lượng");
        sdoFormChinh.add(lblSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, 60, 20));

        lblTienCoc.setBackground(new java.awt.Color(255, 255, 255));
        lblTienCoc.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblTienCoc.setForeground(new java.awt.Color(153, 153, 153));
        lblTienCoc.setText("Tiền Cọc");
        sdoFormChinh.add(lblTienCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 50, 20));

        lblSoDienThoai.setBackground(new java.awt.Color(255, 255, 255));
        lblSoDienThoai.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblSoDienThoai.setForeground(new java.awt.Color(153, 153, 153));
        lblSoDienThoai.setText("Số Điện Thoại");
        sdoFormChinh.add(lblSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 90, 20));

        lblGhiChu.setBackground(new java.awt.Color(255, 255, 255));
        lblGhiChu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblGhiChu.setForeground(new java.awt.Color(153, 153, 153));
        lblGhiChu.setText("Ghi Chú");
        sdoFormChinh.add(lblGhiChu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 60, 20));

        lblLoaiKhach.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiKhach.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblLoaiKhach.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiKhach.setText("Loại Khách");
        sdoFormChinh.add(lblLoaiKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 140, 70, 20));

        cboLoaiPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboLoaiPhong.setForeground(new java.awt.Color(62, 73, 95));
        cboLoaiPhong.setBorder(null);
        sdoFormChinh.add(cboLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, 100, 20));

        lblSetNgayTao.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetNgayTao.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh.add(lblSetNgayTao, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 80, 90, 20));

        dateNgayDi.setBackground(new java.awt.Color(255, 255, 255));
        dateNgayDi.setForeground(new java.awt.Color(62, 73, 95));
        dateNgayDi.setToolTipText("");
        dateNgayDi.setDateFormatString("dd-MM-yyyy");
        dateNgayDi.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateNgayDiPropertyChange(evt);
            }
        });
        sdoFormChinh.add(dateNgayDi, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 110, 20));

        lblMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblMaPhieu.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaPhieu.setForeground(new java.awt.Color(153, 153, 153));
        lblMaPhieu.setText("Mã Phiếu");
        sdoFormChinh.add(lblMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 60, 20));

        lblNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        lblNhanVien.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        lblNhanVien.setText("Nhân Viên");
        sdoFormChinh.add(lblNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 70, 20));

        dateNgayDen.setBackground(new java.awt.Color(255, 255, 255));
        dateNgayDen.setForeground(new java.awt.Color(62, 73, 95));
        dateNgayDen.setToolTipText("");
        dateNgayDen.setDateFormatString("dd-MM-yyyy");
        dateNgayDen.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateNgayDenPropertyChange(evt);
            }
        });
        sdoFormChinh.add(dateNgayDen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 110, 20));

        cboLoaiKhach.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboLoaiKhach.setForeground(new java.awt.Color(62, 73, 95));
        cboLoaiKhach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khách Đơn", "Khách Đoàn" }));
        cboLoaiKhach.setBorder(null);
        sdoFormChinh.add(cboLoaiKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 100, 20));

        txtTenKhach.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtTenKhach.setForeground(new java.awt.Color(62, 73, 95));
        txtTenKhach.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenKhach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhachActionPerformed(evt);
            }
        });
        txtTenKhach.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTenKhachKeyReleased(evt);
            }
        });
        sdoFormChinh.add(txtTenKhach, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 100, 20));

        txtSoDienThoai.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(62, 73, 95));
        txtSoDienThoai.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });
        txtSoDienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoDienThoaiKeyReleased(evt);
            }
        });
        sdoFormChinh.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 100, 20));

        txtSoLuong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtSoLuong.setForeground(new java.awt.Color(62, 73, 95));
        txtSoLuong.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });
        txtSoLuong.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSoLuongKeyReleased(evt);
            }
        });
        sdoFormChinh.add(txtSoLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 80, 20));

        txtTimKiem.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtTimKiem.setForeground(new java.awt.Color(62, 73, 95));
        txtTimKiem.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
        });
        sdoFormChinh.add(txtTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 230, 100, 30));

        txtNhanVien.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        txtNhanVien.setForeground(new java.awt.Color(62, 73, 95));
        txtNhanVien.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhanVienActionPerformed(evt);
            }
        });
        txtNhanVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNhanVienKeyReleased(evt);
            }
        });
        sdoFormChinh.add(txtNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 80, 80, 20));

        lblThem.setBackground(new java.awt.Color(255, 255, 255));
        lblThem.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThem.setForeground(new java.awt.Color(33, 150, 243));
        lblThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add (1).png"))); // NOI18N
        lblThem.setText("Thêm");
        lblThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThemMouseClicked(evt);
            }
        });
        sdoFormChinh.add(lblThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 230, 60, 30));

        lblSetMaPhieu.setBackground(new java.awt.Color(255, 255, 255));
        lblSetMaPhieu.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblSetMaPhieu.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh.add(lblSetMaPhieu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 70, 20));

        lblGioPhutVao.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutVao.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblGioPhutVao.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutVao.setText("00:00");
        lblGioPhutVao.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoFormChinh.add(lblGioPhutVao, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 40, 20));

        lblGioPhutRa.setBackground(new java.awt.Color(255, 255, 255));
        lblGioPhutRa.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblGioPhutRa.setForeground(new java.awt.Color(62, 73, 95));
        lblGioPhutRa.setText("00:00");
        lblGioPhutRa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        sdoFormChinh.add(lblGioPhutRa, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 40, 20));

        sdoDatPhong.setBackground(new java.awt.Color(255, 255, 255));
        sdoDatPhong.setMinimumSize(new java.awt.Dimension(1150, 440));
        sdoDatPhong.setPreferredSize(new java.awt.Dimension(1150, 440));
        sdoDatPhong.setShadowOpacity(0.4F);
        sdoDatPhong.setShadowSize(9);
        sdoDatPhong.setShadowType(HELPER.ShadowType.BOT);
        sdoDatPhong.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        scrDatPhong.setBackground(new java.awt.Color(255, 255, 255));
        scrDatPhong.setBorder(null);

        tblDatPhong.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        tblDatPhong.setForeground(new java.awt.Color(62, 73, 95));
        tblDatPhong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Phiếu", "Tên Khách", "SĐT", "Số Lượng", "Ngày Đến", "Ngày Đi", "Tiền Cọc", "Loại Phòng", "Loại Khách", "Ghi Chú", "Nhân Viên", "Ngày Tạo", "", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatPhong.setRowHeight(30);
        tblDatPhong.setShowHorizontalLines(false);
        tblDatPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatPhongMouseClicked(evt);
            }
        });
        scrDatPhong.setViewportView(tblDatPhong);
        if (tblDatPhong.getColumnModel().getColumnCount() > 0) {
            tblDatPhong.getColumnModel().getColumn(12).setMaxWidth(40);
            tblDatPhong.getColumnModel().getColumn(13).setMaxWidth(40);
        }

        sdoDatPhong.add(scrDatPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1110, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sdoFormChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(sdoDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 1150, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sdoFormChinh, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sdoDatPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtGhiChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGhiChuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGhiChuActionPerformed

    private void txtTienCocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTienCocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTienCocActionPerformed

    private void lblLamMoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLamMoiMouseClicked
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_lblLamMoiMouseClicked

    private void lblTimKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTimKiemMouseClicked
        // TODO add your handling code here:
        add();
        load();
    }//GEN-LAST:event_lblTimKiemMouseClicked

    private void tblDatPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatPhongMouseClicked
        // TODO add your handling code here:
        int row = tblDatPhong.getSelectedRow();
        int column = tblDatPhong.getSelectedColumn();
        maNhanVien = tblDatPhong.getValueAt(row, 0).toString();
        if (tblDatPhong.getValueAt(row, column) != null && tblDatPhong.getValueAt(row, column + 1) != null || tblDatPhong.getValueAt(row, column) != null && tblDatPhong.getValueAt(row, column - 1) != null) {
            fill(row);
        } else if (tblDatPhong.getValueAt(row, column) == null && tblDatPhong.getValueAt(row, column - 1) == null && tblDatPhong.getValueAt(row, column - 2) == null) {
            delete(row);
            load();
        } else if (tblDatPhong.getValueAt(row, column) == null && tblDatPhong.getValueAt(row, column - 1) == null && tblDatPhong.getValueAt(row, column + 1) == null) {
            edit(row);
            load();
        } else if (tblDatPhong.getValueAt(row, column) == null && tblDatPhong.getValueAt(row, column - 1) != null && tblDatPhong.getValueAt(row, column + 1) == null) {
            loadTaiKhoan();
        }
    }//GEN-LAST:event_tblDatPhongMouseClicked

    private void dateNgayDiPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateNgayDiPropertyChange
        // TODO add your handling code here:
        if (dateNgayDi.getDate() != null) {
            Calendar calendar = Calendar.getInstance();
            calendar.add(Calendar.YEAR, -18);
            dateNgayDi.setMaxSelectableDate(calendar.getTime());
        }
    }//GEN-LAST:event_dateNgayDiPropertyChange

    private void txtGhiChuKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGhiChuKeyReleased
        // TODO add your handling code here:
        txtGhiChu.setText(txtGhiChu.getText().replaceAll("[1234567890[*/+-]]", ""));
    }//GEN-LAST:event_txtGhiChuKeyReleased

    private void txtTienCocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTienCocKeyReleased
        // TODO add your handling code here:
        txtTienCoc.setText(txtTienCoc.getText().replaceAll("[abcdefghijklmnopqrstuvwxyz[*/-]]", ""));
    }//GEN-LAST:event_txtTienCocKeyReleased

    private void dateNgayDenPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateNgayDenPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_dateNgayDenPropertyChange

    private void txtTenKhachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachActionPerformed

    private void txtTenKhachKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTenKhachKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhachKeyReleased

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void txtSoDienThoaiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoDienThoaiKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiKeyReleased

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtSoLuongKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSoLuongKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongKeyReleased

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void txtNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhanVienActionPerformed

    private void txtNhanVienKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNhanVienKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNhanVienKeyReleased

    private void lblThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblThemMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cboLoaiKhach;
    private javax.swing.JComboBox<String> cboLoaiPhong;
    private com.toedter.calendar.JDateChooser dateNgayDen;
    private com.toedter.calendar.JDateChooser dateNgayDi;
    private javax.swing.JLabel lblDanhSachDatPhong;
    private javax.swing.JLabel lblGhiChu;
    private javax.swing.JLabel lblGioPhutRa;
    private javax.swing.JLabel lblGioPhutVao;
    private javax.swing.JLabel lblLamMoi;
    private javax.swing.JLabel lblLoaiKhach;
    private javax.swing.JLabel lblLoaiPhong;
    private javax.swing.JLabel lblMaPhieu;
    private javax.swing.JLabel lblNgayDen;
    private javax.swing.JLabel lblNgayDi;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSetMaPhieu;
    private javax.swing.JLabel lblSetNgayTao;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel lblSoLuong;
    private javax.swing.JLabel lblTenKhach;
    private javax.swing.JLabel lblThem;
    private javax.swing.JLabel lblTienCoc;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JScrollPane scrDatPhong;
    private HELPER.PanelShadow sdoDatPhong;
    private HELPER.PanelShadow sdoFormChinh;
    private javax.swing.JTable tblDatPhong;
    private javax.swing.JTextField txtGhiChu;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenKhach;
    private javax.swing.JTextField txtTienCoc;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
