/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_LoaiSanPham;
import BLL.BLL_SanPham;
import DTO.DTO_LoaiSanPham;
import DTO.DTO_SanPham;
import HELPER.MyCombobox;
import javax.swing.JOptionPane;

/**
 *
 * @author Trung Thanh
 */
public class GUI_dal_SanPham extends javax.swing.JDialog {

    /**
     * Creates new form GUI_dal_SanPham
     */
    public GUI_dal_SanPham(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnlsLoaiHangHoa = new HELPER.PanelShadow();
        scrTang = new javax.swing.JScrollPane();
        tblLoaiSanPham = new javax.swing.JTable();
        lblMaLoaiHangHoa = new javax.swing.JLabel();
        lblTenLoaiHangHoa = new javax.swing.JLabel();
        txtTenLoaiHangHoa = new javax.swing.JTextField();
        btnThemLoaiHangHoa = new javax.swing.JLabel();
        lblLoaiHangHoa = new javax.swing.JLabel();
        txtMaLoaiHangHoa = new javax.swing.JTextField();
        pnlsHangHoa = new HELPER.PanelShadow();
        lblMaHangHoa = new javax.swing.JLabel();
        lblTenHangHoa = new javax.swing.JLabel();
        txtTenHangHoa = new javax.swing.JTextField();
        lblLoaiHangHoa_HangHoa = new javax.swing.JLabel();
        cboLoaiHangHoa = new javax.swing.JComboBox<>();
        lblDonVi = new javax.swing.JLabel();
        lblHangHoa = new javax.swing.JLabel();
        lblGiaBan = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        btnThemHangHoa = new javax.swing.JLabel();
        scrLoaiPhong = new javax.swing.JScrollPane();
        tblSanPham = new javax.swing.JTable();
        txtDonViTinh = new javax.swing.JTextField();
        btnExit = new javax.swing.JLabel();
        txtMaHangHoa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlsLoaiHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        pnlsLoaiHangHoa.setMinimumSize(new java.awt.Dimension(560, 280));
        pnlsLoaiHangHoa.setPreferredSize(new java.awt.Dimension(560, 280));
        pnlsLoaiHangHoa.setShadowOpacity(0.3F);
        pnlsLoaiHangHoa.setShadowType(HELPER.ShadowType.BOT_RIGHT);
        pnlsLoaiHangHoa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblLoaiSanPham.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tblLoaiSanPham.setForeground(new java.awt.Color(62, 73, 95));
        tblLoaiSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã", "Tên", "Sửa", "Xóa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLoaiSanPham.setRowHeight(24);
        tblLoaiSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLoaiSanPhamMouseClicked(evt);
            }
        });
        scrTang.setViewportView(tblLoaiSanPham);
        if (tblLoaiSanPham.getColumnModel().getColumnCount() > 0) {
            tblLoaiSanPham.getColumnModel().getColumn(2).setMaxWidth(50);
            tblLoaiSanPham.getColumnModel().getColumn(3).setMaxWidth(50);
        }

        pnlsLoaiHangHoa.add(scrTang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 293, 540));

        lblMaLoaiHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        lblMaLoaiHangHoa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblMaLoaiHangHoa.setForeground(new java.awt.Color(153, 153, 153));
        lblMaLoaiHangHoa.setText("Mã");
        pnlsLoaiHangHoa.add(lblMaLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, 20));

        lblTenLoaiHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        lblTenLoaiHangHoa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTenLoaiHangHoa.setForeground(new java.awt.Color(153, 153, 153));
        lblTenLoaiHangHoa.setText("Tên");
        pnlsLoaiHangHoa.add(lblTenLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, 20));

        txtTenLoaiHangHoa.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        txtTenLoaiHangHoa.setForeground(new java.awt.Color(62, 73, 95));
        txtTenLoaiHangHoa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenLoaiHangHoa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlsLoaiHangHoa.add(txtTenLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 142, 20));

        btnThemLoaiHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        btnThemLoaiHangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add (2).png"))); // NOI18N
        btnThemLoaiHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemLoaiHangHoaMouseClicked(evt);
            }
        });
        pnlsLoaiHangHoa.add(btnThemLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 30, 30));

        lblLoaiHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiHangHoa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblLoaiHangHoa.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiHangHoa.setText("Loại hàng hóa/ dịch vụ");
        pnlsLoaiHangHoa.add(lblLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        txtMaLoaiHangHoa.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        txtMaLoaiHangHoa.setForeground(new java.awt.Color(62, 73, 95));
        txtMaLoaiHangHoa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMaLoaiHangHoa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlsLoaiHangHoa.add(txtMaLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 60, 20));

        jPanel2.add(pnlsLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 313, 680));

        pnlsHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        pnlsHangHoa.setMinimumSize(new java.awt.Dimension(560, 280));
        pnlsHangHoa.setPreferredSize(new java.awt.Dimension(560, 280));
        pnlsHangHoa.setShadowOpacity(0.3F);
        pnlsHangHoa.setShadowType(HELPER.ShadowType.BOT_RIGHT);
        pnlsHangHoa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMaHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        lblMaHangHoa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblMaHangHoa.setForeground(new java.awt.Color(153, 153, 153));
        lblMaHangHoa.setText("Mã");
        pnlsHangHoa.add(lblMaHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, -1, -1));

        lblTenHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        lblTenHangHoa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTenHangHoa.setForeground(new java.awt.Color(153, 153, 153));
        lblTenHangHoa.setText("Tên");
        pnlsHangHoa.add(lblTenHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        txtTenHangHoa.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        txtTenHangHoa.setForeground(new java.awt.Color(62, 73, 95));
        txtTenHangHoa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTenHangHoa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlsHangHoa.add(txtTenHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, 142, 25));

        lblLoaiHangHoa_HangHoa.setBackground(new java.awt.Color(255, 255, 255));
        lblLoaiHangHoa_HangHoa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblLoaiHangHoa_HangHoa.setForeground(new java.awt.Color(153, 153, 153));
        lblLoaiHangHoa_HangHoa.setText("Loại hàng hóa");
        pnlsHangHoa.add(lblLoaiHangHoa_HangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        cboLoaiHangHoa.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        cboLoaiHangHoa.setForeground(new java.awt.Color(62, 73, 95));
        cboLoaiHangHoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiHangHoa.setToolTipText("");
        cboLoaiHangHoa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        pnlsHangHoa.add(cboLoaiHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 130, -1));

        lblDonVi.setBackground(new java.awt.Color(255, 255, 255));
        lblDonVi.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblDonVi.setForeground(new java.awt.Color(153, 153, 153));
        lblDonVi.setText("Đơn vị");
        pnlsHangHoa.add(lblDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, -1, -1));

        lblHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        lblHangHoa.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblHangHoa.setForeground(new java.awt.Color(153, 153, 153));
        lblHangHoa.setText("Hàng hóa/ dịch vụ");
        pnlsHangHoa.add(lblHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        lblGiaBan.setBackground(new java.awt.Color(255, 255, 255));
        lblGiaBan.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblGiaBan.setForeground(new java.awt.Color(153, 153, 153));
        lblGiaBan.setText("Giá bán");
        pnlsHangHoa.add(lblGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 60, -1, -1));

        txtGiaBan.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        txtGiaBan.setForeground(new java.awt.Color(62, 73, 95));
        txtGiaBan.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtGiaBan.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlsHangHoa.add(txtGiaBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, 70, 25));

        btnThemHangHoa.setBackground(new java.awt.Color(255, 255, 255));
        btnThemHangHoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemHangHoa.setForeground(new java.awt.Color(0, 153, 255));
        btnThemHangHoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/add (2).png"))); // NOI18N
        btnThemHangHoa.setText("THÊM");
        btnThemHangHoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemHangHoaMouseClicked(evt);
            }
        });
        pnlsHangHoa.add(btnThemHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 70, 30));

        tblSanPham.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        tblSanPham.setForeground(new java.awt.Color(62, 73, 95));
        tblSanPham.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Loại hàng hóa", "Mã", "Tên", "Đơn vị", "Giá bán", "Sửa", "Xóa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSanPham.setRowHeight(24);
        tblSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSanPhamMouseClicked(evt);
            }
        });
        scrLoaiPhong.setViewportView(tblSanPham);
        if (tblSanPham.getColumnModel().getColumnCount() > 0) {
            tblSanPham.getColumnModel().getColumn(5).setMaxWidth(40);
            tblSanPham.getColumnModel().getColumn(6).setMaxWidth(40);
        }

        pnlsHangHoa.add(scrLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 720, 540));

        txtDonViTinh.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        txtDonViTinh.setForeground(new java.awt.Color(62, 73, 95));
        txtDonViTinh.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtDonViTinh.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlsHangHoa.add(txtDonViTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 60, 25));

        btnExit.setBackground(new java.awt.Color(255, 255, 255));
        btnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/close (1).png"))); // NOI18N
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });
        pnlsHangHoa.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 40, 30));

        txtMaHangHoa.setFont(new java.awt.Font("DialogInput", 1, 15)); // NOI18N
        txtMaHangHoa.setForeground(new java.awt.Color(62, 73, 95));
        txtMaHangHoa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtMaHangHoa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        pnlsHangHoa.add(txtMaHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, 25));

        jPanel2.add(pnlsHangHoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 760, 680));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -1, 1070, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblLoaiSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLoaiSanPhamMouseClicked
        tableLoaiSanPham();
    }//GEN-LAST:event_tblLoaiSanPhamMouseClicked

    private void tblSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSanPhamMouseClicked
        tableSanPham();
    }//GEN-LAST:event_tblSanPhamMouseClicked

    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        exit();
    }//GEN-LAST:event_btnExitMouseClicked

    private void btnThemLoaiHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemLoaiHangHoaMouseClicked
        if(add_or_update_LoaiSanPham)
        {
            addLoaiSanPham();
        }else{
            updateLoaiSanPham();
            add_or_update_LoaiSanPham = true;
            txtMaLoaiHangHoa.setEditable(true);
        }
    }//GEN-LAST:event_btnThemLoaiHangHoaMouseClicked

    private void btnThemHangHoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemHangHoaMouseClicked
        
        if(add_or_update_SanPham)
        {
            addSanPham();
        }else{
            updateSanPham();
            add_or_update_SanPham = true;
            txtMaHangHoa.setEditable(true);
        }
    }//GEN-LAST:event_btnThemHangHoaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_dal_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_dal_SanPham dialog = new GUI_dal_SanPham(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnExit;
    private javax.swing.JLabel btnThemHangHoa;
    private javax.swing.JLabel btnThemLoaiHangHoa;
    private javax.swing.JComboBox<String> cboLoaiHangHoa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblDonVi;
    private javax.swing.JLabel lblGiaBan;
    private javax.swing.JLabel lblHangHoa;
    private javax.swing.JLabel lblLoaiHangHoa;
    private javax.swing.JLabel lblLoaiHangHoa_HangHoa;
    private javax.swing.JLabel lblMaHangHoa;
    private javax.swing.JLabel lblMaLoaiHangHoa;
    private javax.swing.JLabel lblTenHangHoa;
    private javax.swing.JLabel lblTenLoaiHangHoa;
    private HELPER.PanelShadow pnlsHangHoa;
    private HELPER.PanelShadow pnlsLoaiHangHoa;
    private javax.swing.JScrollPane scrLoaiPhong;
    private javax.swing.JScrollPane scrTang;
    private javax.swing.JTable tblLoaiSanPham;
    private javax.swing.JTable tblSanPham;
    private javax.swing.JTextField txtDonViTinh;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtMaHangHoa;
    private javax.swing.JTextField txtMaLoaiHangHoa;
    private javax.swing.JTextField txtTenHangHoa;
    private javax.swing.JTextField txtTenLoaiHangHoa;
    // End of variables declaration//GEN-END:variables
void init()
{
    BLL_LoaiSanPham.fillTableLoaiSanPham(tblLoaiSanPham);
    BLL_SanPham.fillTableSanPham(tblSanPham);
    BLL_LoaiSanPham.fillComboboxLoaiSanPham(cboLoaiHangHoa);
    txtGiaBan.setText("0");
}

void exit()
{
    dispose();
}

void clearTextLoaiSanPham()
{
    txtMaLoaiHangHoa.setText("");
    txtTenLoaiHangHoa.setText("");
}    

void addLoaiSanPham()
{
    DTO_LoaiSanPham dto_LoaiSanPham = new DTO_LoaiSanPham(txtMaLoaiHangHoa.getText(), txtTenLoaiHangHoa.getText());
    BLL_LoaiSanPham.add(dto_LoaiSanPham);
    clearTextLoaiSanPham();
    BLL_LoaiSanPham.fillTableLoaiSanPham(tblLoaiSanPham);
}

void updateLoaiSanPham()
{
    DTO_LoaiSanPham dto_LoaiSanPham = new DTO_LoaiSanPham(txtMaLoaiHangHoa.getText(), txtTenLoaiHangHoa.getText());
    BLL_LoaiSanPham.update(dto_LoaiSanPham);
    clearTextLoaiSanPham();
    BLL_LoaiSanPham.fillTableLoaiSanPham(tblLoaiSanPham);
}

// khi biến cục bộ là true thì btn ADD là add, false là update
    boolean add_or_update_LoaiSanPham = true;
    
void tableLoaiSanPham()
{
    int row = tblLoaiSanPham.getSelectedRow();
    int column = tblLoaiSanPham.getSelectedColumn();
    if(column == 3)
    {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION)
        {
            String maLoaiSanPham = tblLoaiSanPham.getValueAt(row, 0).toString();
            BLL_LoaiSanPham.delete(maLoaiSanPham);
            clearTextLoaiSanPham();
            BLL_LoaiSanPham.fillTableLoaiSanPham(tblLoaiSanPham);
            add_or_update_LoaiSanPham = true;
            txtMaLoaiHangHoa.setEditable(true);
        } 
    }
    if(column == 2)
    {
        String maLoaiSanPham = tblLoaiSanPham.getValueAt(row, 0).toString();
        String tenLoaiSanPham = tblLoaiSanPham.getValueAt(row, 1).toString();
        txtMaLoaiHangHoa.setText(maLoaiSanPham);
        txtTenLoaiHangHoa.setText(tenLoaiSanPham);
        add_or_update_LoaiSanPham = false;
        txtMaLoaiHangHoa.setEditable(false);
    }
}

void clearTextSanPham()
{
    txtMaHangHoa.setText("");
    txtTenHangHoa.setText("");
    txtDonViTinh.setText("");
    txtGiaBan.setText("0");
}

void addSanPham()
{   
    MyCombobox myCbb = (MyCombobox) cboLoaiHangHoa.getSelectedItem();
    DTO_SanPham dto_SanPham = new DTO_SanPham(txtMaHangHoa.getText(), txtTenHangHoa.getText(), myCbb.MaString(), txtDonViTinh.getText(), HELPER.HELPER_ChuyenDoi.getSoDouble(txtGiaBan.getText()));
    BLL_SanPham.add(dto_SanPham);
    clearTextSanPham();
    BLL_SanPham.fillTableSanPham(tblSanPham);
    
}

void updateSanPham()
{
    MyCombobox myCbb = (MyCombobox) cboLoaiHangHoa.getSelectedItem();
    DTO_SanPham dto_SanPham = new DTO_SanPham(txtMaHangHoa.getText(), txtTenHangHoa.getText(), myCbb.MaString(), txtDonViTinh.getText(), HELPER.HELPER_ChuyenDoi.getSoDouble(txtGiaBan.getText()));
    BLL_SanPham.update(dto_SanPham);
    clearTextSanPham();
    BLL_SanPham.fillTableSanPham(tblSanPham);
}

boolean add_or_update_SanPham = true;

void tableSanPham()
{
    int row = tblSanPham.getSelectedRow();
    int column = tblSanPham.getSelectedColumn();
    if(column == 6)
    {
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn xóa không ?", "Xóa", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION)
        {
            String maSanPham = tblSanPham.getValueAt(row, 1).toString();
            BLL_SanPham.delete(maSanPham);
            clearTextSanPham();
            BLL_SanPham.fillTableSanPham(tblSanPham);
            add_or_update_SanPham = true;
            txtMaHangHoa.setEditable(true);
        } 
    }
    if(column == 5)
    {
        String tenLoaiSanPham = tblSanPham.getValueAt(row, 0).toString();
        BLL_LoaiSanPham.fillTableValueTenLoaiSanPhamToCombobox(cboLoaiHangHoa, tenLoaiSanPham);
        txtMaHangHoa.setText(tblSanPham.getValueAt(row, 1).toString());
        txtTenHangHoa.setText(tblSanPham.getValueAt(row, 2).toString());
        txtDonViTinh.setText(tblSanPham.getValueAt(row, 3).toString());
        txtGiaBan.setText(tblSanPham.getValueAt(row, 4).toString());
        add_or_update_SanPham = false;
        txtMaHangHoa.setEditable(false);
    }
}

}
