/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.BLL_ThongKe;
import HELPER.HELPER_ChuyenDoi;
import HELPER.ModelPolarAreaChart;
import HELPER.ModelChart;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Trung Thanh
 */
public class GUI_pnl_ThongKe extends javax.swing.JPanel {

    /**
     * Creates new form GUI_pnl_ThongKe
     */
    public GUI_pnl_ThongKe() {
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sdoChucNang = new LIB.PanelShadow();
        lblThongKe = new javax.swing.JLabel();
        lblThongKeTrongNgay = new javax.swing.JLabel();
        dateNgay = new com.toedter.calendar.JDateChooser();
        sdoFormChinh1 = new LIB.PanelShadow();
        lblSetNgayTao1 = new javax.swing.JLabel();
        lblMaNhanVien11 = new javax.swing.JLabel();
        lblConLai = new javax.swing.JLabel();
        lblMaNhanVien2 = new javax.swing.JLabel();
        lblMaNhanVien14 = new javax.swing.JLabel();
        lblMaNhanVien15 = new javax.swing.JLabel();
        lblMaNhanVien16 = new javax.swing.JLabel();
        lblMaNhanVien18 = new javax.swing.JLabel();
        lblMaNhanVien19 = new javax.swing.JLabel();
        lblTienPhong = new javax.swing.JLabel();
        lblTienDichVu = new javax.swing.JLabel();
        lblDatCoc = new javax.swing.JLabel();
        lblDoanhThu = new javax.swing.JLabel();
        lblChiPhi = new javax.swing.JLabel();
        sdoFormChinh2 = new LIB.PanelShadow();
        lblPhanTramCuaPhongTrong = new javax.swing.JLabel();
        lblPhongTrong = new javax.swing.JLabel();
        lblMaNhanVien7 = new javax.swing.JLabel();
        lblDangO = new javax.swing.JLabel();
        lblMaNhanVien8 = new javax.swing.JLabel();
        lblDaTraPhong = new javax.swing.JLabel();
        lblMaNhanVien9 = new javax.swing.JLabel();
        lblDatTruoc = new javax.swing.JLabel();
        lblMaNhanVien10 = new javax.swing.JLabel();
        lblMaNhanVien13 = new javax.swing.JLabel();
        lblMaNhanVien20 = new javax.swing.JLabel();
        sdoFormChinh3 = new LIB.PanelShadow();
        barChartTheoLoaiPhong = new HELPER.Chart();
        sdoFormChinh4 = new LIB.PanelShadow();
        lblSetNgayTao4 = new javax.swing.JLabel();
        lblMaNhanVien12 = new javax.swing.JLabel();
        pieChartTheoLoaiPhong = new HELPER.PolarAreaChart();
        sdoFormChinh5 = new LIB.PanelShadow();
        lblSetNgayTao5 = new javax.swing.JLabel();
        lblMaNhanVien22 = new javax.swing.JLabel();
        sdoFormChinh6 = new LIB.PanelShadow();
        lblSetNgayTao6 = new javax.swing.JLabel();
        lblMaNhanVien23 = new javax.swing.JLabel();
        chart2 = new HELPER.Chart();
        barChartKhachDenTheoGio = new HELPER.Chart();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sdoChucNang.setBackground(new java.awt.Color(255, 255, 255));
        sdoChucNang.setMinimumSize(new java.awt.Dimension(1150, 60));
        sdoChucNang.setPreferredSize(new java.awt.Dimension(1150, 60));
        sdoChucNang.setShadowOpacity(0.4F);
        sdoChucNang.setShadowSize(9);
        sdoChucNang.setShadowType(LIB.ShadowType.BOT);
        sdoChucNang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblThongKe.setBackground(new java.awt.Color(255, 255, 255));
        lblThongKe.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblThongKe.setForeground(new java.awt.Color(33, 150, 243));
        lblThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/data-analytics.png"))); // NOI18N
        lblThongKe.setText("Thống kê");
        lblThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeMouseClicked(evt);
            }
        });
        sdoChucNang.add(lblThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 100, 20));

        lblThongKeTrongNgay.setBackground(new java.awt.Color(255, 255, 255));
        lblThongKeTrongNgay.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblThongKeTrongNgay.setForeground(new java.awt.Color(153, 153, 153));
        lblThongKeTrongNgay.setText("Thống Kê Trong Ngày");
        sdoChucNang.add(lblThongKeTrongNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 130, 20));

        dateNgay.setBackground(new java.awt.Color(255, 255, 255));
        dateNgay.setForeground(new java.awt.Color(62, 73, 95));
        dateNgay.setDateFormatString("dd-MM-yyyy");
        sdoChucNang.add(dateNgay, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 100, 20));

        add(sdoChucNang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 60));

        sdoFormChinh1.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao1.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao1.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao1.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh1.add(lblSetNgayTao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lblMaNhanVien11.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien11.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien11.setForeground(new java.awt.Color(62, 73, 95));
        lblMaNhanVien11.setText("Thu / Chi Trong Ngày");
        sdoFormChinh1.add(lblMaNhanVien11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        lblConLai.setBackground(new java.awt.Color(255, 255, 255));
        lblConLai.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblConLai.setForeground(new java.awt.Color(97, 177, 90));
        lblConLai.setText("0");
        sdoFormChinh1.add(lblConLai, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 80, 30));

        lblMaNhanVien2.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien2.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien2.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien2.setText("Tiền phòng");
        sdoFormChinh1.add(lblMaNhanVien2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 80, 30));

        lblMaNhanVien14.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien14.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien14.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien14.setText("Dịch vụ");
        sdoFormChinh1.add(lblMaNhanVien14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 60, 30));

        lblMaNhanVien15.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien15.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien15.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien15.setText("Đặt cọc");
        sdoFormChinh1.add(lblMaNhanVien15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 80, 30));

        lblMaNhanVien16.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien16.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien16.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien16.setText("Doanh thu");
        sdoFormChinh1.add(lblMaNhanVien16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 80, 30));

        lblMaNhanVien18.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien18.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien18.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien18.setText("Chi phí");
        sdoFormChinh1.add(lblMaNhanVien18, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 80, 30));

        lblMaNhanVien19.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien19.setFont(new java.awt.Font("Calibri", 0, 13)); // NOI18N
        lblMaNhanVien19.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien19.setText("Còn lại");
        sdoFormChinh1.add(lblMaNhanVien19, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 80, 30));

        lblTienPhong.setBackground(new java.awt.Color(255, 255, 255));
        lblTienPhong.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTienPhong.setForeground(new java.awt.Color(97, 177, 90));
        lblTienPhong.setText("0");
        sdoFormChinh1.add(lblTienPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 80, 30));

        lblTienDichVu.setBackground(new java.awt.Color(255, 255, 255));
        lblTienDichVu.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblTienDichVu.setForeground(new java.awt.Color(97, 177, 90));
        lblTienDichVu.setText("0");
        sdoFormChinh1.add(lblTienDichVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 80, 30));

        lblDatCoc.setBackground(new java.awt.Color(255, 255, 255));
        lblDatCoc.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblDatCoc.setForeground(new java.awt.Color(97, 177, 90));
        lblDatCoc.setText("0");
        sdoFormChinh1.add(lblDatCoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 50, 80, 30));

        lblDoanhThu.setBackground(new java.awt.Color(255, 255, 255));
        lblDoanhThu.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblDoanhThu.setForeground(new java.awt.Color(97, 177, 90));
        lblDoanhThu.setText("0");
        sdoFormChinh1.add(lblDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 70, 30));

        lblChiPhi.setBackground(new java.awt.Color(255, 255, 255));
        lblChiPhi.setFont(new java.awt.Font("Calibri", 1, 13)); // NOI18N
        lblChiPhi.setForeground(new java.awt.Color(255, 51, 51));
        lblChiPhi.setText("0");
        sdoFormChinh1.add(lblChiPhi, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 50, 80, 30));

        add(sdoFormChinh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 60, 600, 110));

        sdoFormChinh2.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPhanTramCuaPhongTrong.setBackground(new java.awt.Color(255, 255, 255));
        lblPhanTramCuaPhongTrong.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblPhanTramCuaPhongTrong.setForeground(new java.awt.Color(62, 73, 95));
        lblPhanTramCuaPhongTrong.setText("0.00%");
        sdoFormChinh2.add(lblPhanTramCuaPhongTrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 50, 40));

        lblPhongTrong.setBackground(new java.awt.Color(97, 177, 90));
        lblPhongTrong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblPhongTrong.setForeground(new java.awt.Color(255, 255, 255));
        lblPhongTrong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPhongTrong.setText("0");
        lblPhongTrong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPhongTrong.setOpaque(true);
        sdoFormChinh2.add(lblPhongTrong, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));

        lblMaNhanVien7.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien7.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMaNhanVien7.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNhanVien7.setText("Có Khách");
        lblMaNhanVien7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoFormChinh2.add(lblMaNhanVien7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 84, 60, -1));

        lblDangO.setBackground(new java.awt.Color(255, 142, 113));
        lblDangO.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblDangO.setForeground(new java.awt.Color(255, 255, 255));
        lblDangO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangO.setText("0");
        lblDangO.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDangO.setOpaque(true);
        sdoFormChinh2.add(lblDangO, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 40, 40));

        lblMaNhanVien8.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien8.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMaNhanVien8.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNhanVien8.setText("Trả Phòng");
        lblMaNhanVien8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoFormChinh2.add(lblMaNhanVien8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 84, 60, -1));

        lblDaTraPhong.setBackground(new java.awt.Color(240, 165, 0));
        lblDaTraPhong.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblDaTraPhong.setForeground(new java.awt.Color(255, 255, 255));
        lblDaTraPhong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDaTraPhong.setText("0");
        lblDaTraPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDaTraPhong.setOpaque(true);
        sdoFormChinh2.add(lblDaTraPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 40, 40));

        lblMaNhanVien9.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien9.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMaNhanVien9.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNhanVien9.setText("Công Suất");
        sdoFormChinh2.add(lblMaNhanVien9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 84, 70, -1));

        lblDatTruoc.setBackground(new java.awt.Color(102, 153, 255));
        lblDatTruoc.setFont(new java.awt.Font("Calibri", 1, 16)); // NOI18N
        lblDatTruoc.setForeground(new java.awt.Color(255, 255, 255));
        lblDatTruoc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDatTruoc.setText("0");
        lblDatTruoc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDatTruoc.setOpaque(true);
        sdoFormChinh2.add(lblDatTruoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 40, 40));

        lblMaNhanVien10.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien10.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMaNhanVien10.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNhanVien10.setText("Đặt Trước");
        lblMaNhanVien10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoFormChinh2.add(lblMaNhanVien10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 84, 60, -1));

        lblMaNhanVien13.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien13.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        lblMaNhanVien13.setForeground(new java.awt.Color(153, 153, 153));
        lblMaNhanVien13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMaNhanVien13.setText("Phòng Trống");
        lblMaNhanVien13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sdoFormChinh2.add(lblMaNhanVien13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 84, 80, -1));

        lblMaNhanVien20.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien20.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien20.setForeground(new java.awt.Color(62, 73, 95));
        lblMaNhanVien20.setText("Tình trạng phòng");
        sdoFormChinh2.add(lblMaNhanVien20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 20));

        add(sdoFormChinh2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 550, 110));

        sdoFormChinh3.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barChartTheoLoaiPhong.setMinimumSize(null);
        barChartTheoLoaiPhong.setPreferredSize(new java.awt.Dimension(0, 0));
        sdoFormChinh3.add(barChartTheoLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 520, 330));

        add(sdoFormChinh3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 550, 380));

        sdoFormChinh4.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh4.setShadowOpacity(0.4F);
        sdoFormChinh4.setShadowSize(9);
        sdoFormChinh4.setShadowType(LIB.ShadowType.BOT);
        sdoFormChinh4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao4.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao4.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao4.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh4.add(lblSetNgayTao4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lblMaNhanVien12.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien12.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien12.setText("Theo loại phòng");
        sdoFormChinh4.add(lblMaNhanVien12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, 30));
        sdoFormChinh4.add(pieChartTheoLoaiPhong, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        add(sdoFormChinh4, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 200, 600, 380));

        sdoFormChinh5.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh5.setShadowOpacity(0.4F);
        sdoFormChinh5.setShadowSize(9);
        sdoFormChinh5.setShadowType(LIB.ShadowType.BOT);
        sdoFormChinh5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSetNgayTao5.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao5.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao5.setForeground(new java.awt.Color(62, 73, 95));
        sdoFormChinh5.add(lblSetNgayTao5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 100, 20));

        lblMaNhanVien22.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien22.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien22.setText("Tỷ lệ khách đến theo khung giờ");
        sdoFormChinh5.add(lblMaNhanVien22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, 30));

        sdoFormChinh6.setBackground(new java.awt.Color(255, 255, 255));
        sdoFormChinh6.setShadowOpacity(0.4F);
        sdoFormChinh6.setShadowSize(9);
        sdoFormChinh6.setShadowType(LIB.ShadowType.BOT);

        lblSetNgayTao6.setBackground(new java.awt.Color(255, 255, 255));
        lblSetNgayTao6.setFont(new java.awt.Font("Calibri", 1, 15)); // NOI18N
        lblSetNgayTao6.setForeground(new java.awt.Color(62, 73, 95));

        lblMaNhanVien23.setBackground(new java.awt.Color(255, 255, 255));
        lblMaNhanVien23.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        lblMaNhanVien23.setText("Theo loại phòng");

        javax.swing.GroupLayout sdoFormChinh6Layout = new javax.swing.GroupLayout(sdoFormChinh6);
        sdoFormChinh6.setLayout(sdoFormChinh6Layout);
        sdoFormChinh6Layout.setHorizontalGroup(
            sdoFormChinh6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sdoFormChinh6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(barChartKhachDenTheoGio, javax.swing.GroupLayout.PREFERRED_SIZE, 992, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(sdoFormChinh6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMaNhanVien23, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSetNgayTao6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        sdoFormChinh6Layout.setVerticalGroup(
            sdoFormChinh6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sdoFormChinh6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chart2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(sdoFormChinh6Layout.createSequentialGroup()
                .addGroup(sdoFormChinh6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sdoFormChinh6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lblMaNhanVien23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(lblSetNgayTao6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sdoFormChinh6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(barChartKhachDenTheoGio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        sdoFormChinh5.add(sdoFormChinh6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 1020, 400));

        add(sdoFormChinh5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, 1140, 480));
    }// </editor-fold>//GEN-END:initComponents

    private void lblThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeMouseClicked
        barChart();
        thongKeTrangThaiPhong();
        lineChart();
        pieChart();
        ThongKeNguonTienTrongNgay();

    }//GEN-LAST:event_lblThongKeMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private HELPER.Chart barChartKhachDenTheoGio;
    private HELPER.Chart barChartTheoLoaiPhong;
    private HELPER.Chart chart2;
    private com.toedter.calendar.JDateChooser dateNgay;
    private javax.swing.JLabel lblChiPhi;
    private javax.swing.JLabel lblConLai;
    private javax.swing.JLabel lblDaTraPhong;
    private javax.swing.JLabel lblDangO;
    private javax.swing.JLabel lblDatCoc;
    private javax.swing.JLabel lblDatTruoc;
    private javax.swing.JLabel lblDoanhThu;
    private javax.swing.JLabel lblMaNhanVien10;
    private javax.swing.JLabel lblMaNhanVien11;
    private javax.swing.JLabel lblMaNhanVien12;
    private javax.swing.JLabel lblMaNhanVien13;
    private javax.swing.JLabel lblMaNhanVien14;
    private javax.swing.JLabel lblMaNhanVien15;
    private javax.swing.JLabel lblMaNhanVien16;
    private javax.swing.JLabel lblMaNhanVien18;
    private javax.swing.JLabel lblMaNhanVien19;
    private javax.swing.JLabel lblMaNhanVien2;
    private javax.swing.JLabel lblMaNhanVien20;
    private javax.swing.JLabel lblMaNhanVien22;
    private javax.swing.JLabel lblMaNhanVien23;
    private javax.swing.JLabel lblMaNhanVien7;
    private javax.swing.JLabel lblMaNhanVien8;
    private javax.swing.JLabel lblMaNhanVien9;
    private javax.swing.JLabel lblPhanTramCuaPhongTrong;
    private javax.swing.JLabel lblPhongTrong;
    private javax.swing.JLabel lblSetNgayTao1;
    private javax.swing.JLabel lblSetNgayTao4;
    private javax.swing.JLabel lblSetNgayTao5;
    private javax.swing.JLabel lblSetNgayTao6;
    private javax.swing.JLabel lblThongKe;
    private javax.swing.JLabel lblThongKeTrongNgay;
    private javax.swing.JLabel lblTienDichVu;
    private javax.swing.JLabel lblTienPhong;
    private HELPER.PolarAreaChart pieChartTheoLoaiPhong;
    private LIB.PanelShadow sdoChucNang;
    private LIB.PanelShadow sdoFormChinh1;
    private LIB.PanelShadow sdoFormChinh2;
    private LIB.PanelShadow sdoFormChinh3;
    private LIB.PanelShadow sdoFormChinh4;
    private LIB.PanelShadow sdoFormChinh5;
    private LIB.PanelShadow sdoFormChinh6;
    // End of variables declaration//GEN-END:variables
void init() {
        Date date = new Date();
        dateNgay.setDate(date);

        barChartTheoLoaiPhong.addLegend("Phòng trống", new Color(139, 229, 222));
        barChartTheoLoaiPhong.addLegend("Đang ở", new Color(245, 189, 135));
        barChartTheoLoaiPhong.addLegend("Đặt trước", new Color(135, 189, 245));
        barChartTheoLoaiPhong.addLegend("Phòng trả", new Color(189, 135, 245));
        barChartTheoLoaiPhong.addLegend("Phòng trống", BLL_ThongKe.randomColor());
        barChartTheoLoaiPhong.addLegend("Đang ở", BLL_ThongKe.randomColor());
        barChartTheoLoaiPhong.addLegend("Đặt trước", BLL_ThongKe.randomColor());
        barChartTheoLoaiPhong.addLegend("Phòng trả", BLL_ThongKe.randomColor());

        barChartKhachDenTheoGio.addLegend("Lượng khách đến", BLL_ThongKe.randomColor());

        barChart();
        pieChart();
        lineChart();
        thongKeTrangThaiPhong();
        ThongKeNguonTienTrongNgay();
    }

    void thongKeTrangThaiPhong() {
        ArrayList<Integer> arrList = BLL_ThongKe.ThongKeCacTrangThaiPhong(dateNgay.getDate());
        lblPhongTrong.setText(arrList.get(0).toString());
        lblDangO.setText(arrList.get(1).toString());
        lblDaTraPhong.setText(arrList.get(2).toString());
        lblDatTruoc.setText("0");
        lblPhanTramCuaPhongTrong.setText(arrList.get(3) + "");

    }

    void barChart() {

        ArrayList<int[]> arrList = BLL_ThongKe.ThongKeCacTrangThaiLoaiPhong(dateNgay.getDate());
        int[] obj0 = arrList.get(0);
        int[] obj1 = arrList.get(1);
        int[] obj2 = arrList.get(2);
        int[] obj3 = arrList.get(3);

        barChartTheoLoaiPhong.clear();

        barChartTheoLoaiPhong.addData(new ModelChart("Phòng đơn", new int[]{obj0[0], obj0[1], 3, obj0[2]}));
        barChartTheoLoaiPhong.addData(new ModelChart("Phòng đôi (2 đơn)", new int[]{obj1[0], obj1[1], 2, obj1[2]}));
        barChartTheoLoaiPhong.addData(new ModelChart("Phòng đôi (1 đôi, 1 đơn)", new int[]{obj2[0], obj2[1], 1, obj2[2]}));
        barChartTheoLoaiPhong.addData(new ModelChart("Phòng đôi (2 đôi)", new int[]{obj3[0], obj3[1], 2, obj3[2]}));

        barChartTheoLoaiPhong.start();
    }

    void pieChart() {
        ArrayList<Object[]> arrList = BLL_ThongKe.TienLoaiPhongKiemTrongNgay(dateNgay.getDate());
        pieChartTheoLoaiPhong.clear();
        for (Object[] obj : arrList) {
            pieChartTheoLoaiPhong.addItem(new ModelPolarAreaChart(BLL_ThongKe.randomColor(), obj[0].toString(), (double) obj[1]));
        }
        pieChartTheoLoaiPhong.start();
        pieChartTheoLoaiPhong.addItem(new ModelPolarAreaChart(new Color(52, 148, 203), "Phòng đơn", 440000));
        pieChartTheoLoaiPhong.addItem(new ModelPolarAreaChart(new Color(175, 67, 237), "Phòng đôi (2 đơn)", 300000));
        pieChartTheoLoaiPhong.addItem(new ModelPolarAreaChart(new Color(87, 218, 137), "phòng đôi (1 đơn, 1 đôi)", 400000));
        pieChartTheoLoaiPhong.addItem(new ModelPolarAreaChart(new Color(245, 189, 135), "Phòng đôi (2 đôi) ", 840000));
        pieChartTheoLoaiPhong.start();
    }

    void lineChart() {
        ArrayList<Integer> arrList = BLL_ThongKe.SLKhachVaoTheoGio(dateNgay.getDate());
        barChartKhachDenTheoGio.clear();

        barChartKhachDenTheoGio.addData(new ModelChart("0 giờ - 4 giờ", new int[]{arrList.get(0)}));
        barChartKhachDenTheoGio.addData(new ModelChart("4 giờ - 6 giờ", new int[]{arrList.get(1)}));
        barChartKhachDenTheoGio.addData(new ModelChart("6 giờ - 8 giờ", new int[]{arrList.get(2)}));
        barChartKhachDenTheoGio.addData(new ModelChart("8 giờ - 10 giờ", new int[]{arrList.get(3)}));
        barChartKhachDenTheoGio.addData(new ModelChart("10 giờ - 12 giờ", new int[]{arrList.get(4)}));
        barChartKhachDenTheoGio.addData(new ModelChart("12 giờ - 14 giờ", new int[]{arrList.get(5)}));
        barChartKhachDenTheoGio.addData(new ModelChart("14 giờ - 16 giờ", new int[]{arrList.get(6)}));
        barChartKhachDenTheoGio.addData(new ModelChart("16 giờ - 18 giờ", new int[]{arrList.get(7)}));
        barChartKhachDenTheoGio.addData(new ModelChart("18 giờ - 20 giờ", new int[]{arrList.get(8)}));
        barChartKhachDenTheoGio.addData(new ModelChart("20 giờ - 0 giờ", new int[]{arrList.get(9)}));

        barChartKhachDenTheoGio.start();

    }

    void ThongKeNguonTienTrongNgay() {
        ArrayList<Double> arrList = BLL_ThongKe.NguonTienTrongNgay(dateNgay.getDate());
        lblTienPhong.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(0)));
        lblTienDichVu.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(1)));
        lblDoanhThu.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(2)));
        lblDatCoc.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(3)));
        lblChiPhi.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(4)));
        lblConLai.setText(BLL_ThongKe.SoStringGiaTien(arrList.get(5)));
    }

}
